import { spawn } from "node:child_process";
import { createHash } from "node:crypto";
import {
  access,
  copyFile,
  mkdir,
  mkdtemp,
  readdir,
  readFile,
  rename,
  rm,
  writeFile,
} from "node:fs/promises";
import path from "node:path";
import { readBoundedZipEntries } from "./bounded-zip.js";
import { SlicingWorkerError } from "./failures.js";
import type { WorkerConfig } from "./config.js";

export type OrcaSliceRequest = {
  workspace: string;
  geometryPath: string;
  profilePaths: readonly string[];
  copies: number;
  copiesPerPlate?: readonly number[];
  artifactFormat: "gcode_3mf" | "bgcode" | "gcode";
  requireMetrics?: boolean;
};

export type OrcaSliceOutput = {
  estimatedPrintSeconds: bigint;
  estimatedMaterialMilligrams: bigint;
  thinWallFeatureCount: number;
  supportVolumeRatioPpm: number;
  artifactBytes: Uint8Array;
};

export interface OrcaEngine {
  slice(input: OrcaSliceRequest): Promise<OrcaSliceOutput>;
}

type EngineRuntimeConfig = WorkerConfig["engine"] & {
  maximumArtifactBytes: number;
  maximumDiagnosticBytes: number;
};

type ProfilePaths = {
  settings: string[];
  filaments: string[];
};

function durationSeconds(value: string): number {
  const days = Number(value.match(/(\d+)d/)?.[1] ?? 0);
  const hours = Number(value.match(/(\d+)h/)?.[1] ?? 0);
  const minutes = Number(value.match(/(\d+)m/)?.[1] ?? 0);
  const seconds = Number(value.match(/(\d+)s/)?.[1] ?? 0);
  return days * 86_400 + hours * 3_600 + minutes * 60 + seconds;
}

export function parseOrcaArtifact(
  bytes: Uint8Array,
  expectedVersion: string,
): Omit<OrcaSliceOutput, "artifactBytes"> {
  const source = new TextDecoder("utf-8", { fatal: true }).decode(bytes);
  const version = source.match(
    /^; generated by OrcaSlicer (\S+) on \d{4}-\d{2}-\d{2} at \d{2}:\d{2}:\d{2}$/mu,
  )?.[1];
  if (version !== expectedVersion) {
    throw new SlicingWorkerError(
      "deterministic_invalid",
      "INVALID_PROFILE",
      "Slicer artifact does not match the pinned engine version",
    );
  }
  const duration = source.match(/total estimated time: ([^\n]+)/u)?.[1];
  const grams = source.match(/^; filament used \[g\] = ([\d., ]+)$/mu)?.[1];
  if (!duration || !grams) {
    throw new SlicingWorkerError(
      "deterministic_invalid",
      "INVALID_GEOMETRY",
      "Slicer artifact is missing normalized resource metrics",
    );
  }
  const estimatedPrintSeconds = durationSeconds(duration);
  const estimatedMaterialMilligrams = grams
    .split(",")
    .map((value) => Number(value.trim()))
    .reduce((sum, value) => sum + value * 1_000, 0);
  if (
    !Number.isSafeInteger(estimatedPrintSeconds) ||
    estimatedPrintSeconds < 1 ||
    !Number.isFinite(estimatedMaterialMilligrams) ||
    estimatedMaterialMilligrams <= 0
  ) {
    throw new SlicingWorkerError(
      "deterministic_invalid",
      "INVALID_GEOMETRY",
      "Slicer artifact contains invalid resource metrics",
    );
  }
  const preflight = parsePreflightMetrics(source);
  return {
    estimatedPrintSeconds: BigInt(estimatedPrintSeconds),
    estimatedMaterialMilligrams: BigInt(
      Math.max(1, Math.round(estimatedMaterialMilligrams)),
    ),
    ...preflight,
  };
}

function invalidProductionArtifact(message: string): never {
  throw new SlicingWorkerError(
    "deterministic_invalid",
    "INVALID_GEOMETRY",
    message,
  );
}

function validateCompleteOrcaProgram(bytes: Uint8Array): void {
  let source: string;
  try {
    source = new TextDecoder("utf-8", { fatal: true }).decode(bytes);
  } catch {
    invalidProductionArtifact("Production G-code is not valid UTF-8");
  }
  const lines = source!.split(/\r?\n/u);
  const executableStart = lines.findIndex(
    (line) => line.trim() === "; EXECUTABLE_BLOCK_START",
  );
  const firstLayer = lines.findIndex(
    (line, index) =>
      index > executableStart &&
      /^;\s*(?:CHANGE_LAYER|LAYER_CHANGE)\s*$/u.test(line),
  );
  const executableEnd = lines.findIndex(
    (line, index) =>
      index > firstLayer && line.trim() === "; EXECUTABLE_BLOCK_END",
  );
  const hasStartupCommand = lines
    .slice(executableStart + 1, firstLayer)
    .some((line) => /^\s*[GMT]\d+(?:\.\d+)?(?:\s|$)/iu.test(line));
  if (
    executableStart < 0 ||
    firstLayer < 0 ||
    executableEnd < 0 ||
    !hasStartupCommand
  ) {
    invalidProductionArtifact(
      "Production G-code is missing a complete executable program",
    );
  }
}

export function validateProductionArtifact(
  bytes: Uint8Array,
  format: OrcaSliceRequest["artifactFormat"],
  expectedPlateCount: number,
  expectedVersion: string,
  maximumExpandedBytes: number,
): void {
  if (format === "gcode") {
    parseOrcaArtifact(bytes, expectedVersion);
    validateCompleteOrcaProgram(bytes);
    return;
  }
  if (format !== "gcode_3mf") {
    invalidProductionArtifact("Production artifact format is unsupported");
  }
  const entries = readBoundedZipEntries(bytes, {
    label: "G-code 3MF archive",
    invalidCode: "INVALID_GEOMETRY",
    maximumEntries: 256,
    maximumEntryBytes: maximumExpandedBytes,
    maximumTotalBytes: maximumExpandedBytes,
  });
  const sliceInfo = entries.get("Metadata/slice_info.config");
  if (!sliceInfo || sliceInfo.byteLength === 0) {
    invalidProductionArtifact(
      "G-code 3MF archive is missing its slice information",
    );
  }
  const plateEntries = [...entries.keys()].filter(
    (name) => name.startsWith("Metadata/plate_") && name.endsWith(".gcode"),
  );
  if (plateEntries.length !== expectedPlateCount) {
    invalidProductionArtifact(
      "G-code 3MF archive does not match the accepted plate count",
    );
  }
  for (let plate = 1; plate <= expectedPlateCount; plate += 1) {
    const name = `Metadata/plate_${plate}.gcode`;
    const gcode = entries.get(name);
    const declaredDigest = entries.get(`${name}.md5`);
    if (!gcode || gcode.byteLength === 0 || !declaredDigest) {
      invalidProductionArtifact(
        "G-code 3MF archive has an incomplete plate artifact",
      );
    }
    let expectedDigest: string;
    try {
      expectedDigest = new TextDecoder("utf-8", { fatal: true })
        .decode(declaredDigest)
        .trim();
    } catch {
      invalidProductionArtifact(
        "G-code 3MF archive contains an invalid plate checksum",
      );
    }
    const observedDigest = createHash("md5")
      .update(gcode)
      .digest("hex")
      .toUpperCase();
    if (
      !/^[A-F0-9]{32}$/u.test(expectedDigest!) ||
      expectedDigest !== observedDigest
    ) {
      invalidProductionArtifact(
        "G-code 3MF archive plate checksum does not match its contents",
      );
    }
    parseOrcaArtifact(gcode, expectedVersion);
    validateCompleteOrcaProgram(gcode);
  }
}

function validatedProductionMetrics(
  bytes: Uint8Array,
  input: OrcaSliceRequest,
  platePlan: readonly number[] | null,
  config: EngineRuntimeConfig,
): Omit<OrcaSliceOutput, "artifactBytes"> {
  validateProductionArtifact(
    bytes,
    input.artifactFormat,
    platePlan?.length ?? 1,
    config.version,
    config.maximumArtifactBytes,
  );
  return {
    estimatedPrintSeconds: 1n,
    estimatedMaterialMilligrams: 1n,
    thinWallFeatureCount: 0,
    supportVolumeRatioPpm: 0,
  };
}

function parsePreflightMetrics(source: string): {
  thinWallFeatureCount: number;
  supportVolumeRatioPpm: number;
} {
  let relativeExtrusion = false;
  let absoluteExtrusion = 0;
  let currentFeature: string | null = null;
  let countedCurrentThinFeature = false;
  let totalExtrusion = 0;
  let supportExtrusion = 0;
  let thinWallFeatureCount = 0;
  let retractedExtrusion = 0;
  const numeric = "[-+]?(?:\\d+(?:\\.\\d*)?|\\.\\d+)(?:[eE][-+]?\\d+)?";
  const extrusion = new RegExp(`(?:^|\\s)E(${numeric})(?=\\s|$)`, "u");

  for (const sourceLine of source.split(/\r?\n/u)) {
    const feature = sourceLine.match(/^;\s*FEATURE:\s*(.+?)\s*$/u)?.[1];
    if (feature !== undefined) {
      currentFeature = feature;
      countedCurrentThinFeature = false;
      continue;
    }
    const line = sourceLine.split(";", 1)[0]!.trim();
    if (/^M82(?:\s|$)/u.test(line)) {
      relativeExtrusion = false;
      continue;
    }
    if (/^M83(?:\s|$)/u.test(line)) {
      relativeExtrusion = true;
      continue;
    }
    if (/^G92(?:\s|$)/u.test(line)) {
      const value = line.match(extrusion)?.[1];
      if (value !== undefined) absoluteExtrusion = Number(value);
      continue;
    }
    if (!/^G(?:0?0|0?1)(?:\s|$)/u.test(line)) continue;
    const encodedExtrusion = line.match(extrusion)?.[1];
    if (encodedExtrusion === undefined) continue;
    const value = Number(encodedExtrusion);
    if (!Number.isFinite(value)) continue;
    const delta = relativeExtrusion ? value : value - absoluteExtrusion;
    if (!relativeExtrusion) absoluteExtrusion = value;
    if (delta < 0) {
      retractedExtrusion += -delta;
      continue;
    }
    const restored = Math.min(delta, retractedExtrusion);
    retractedExtrusion -= restored;
    const deposited = delta - restored;
    if (deposited <= 0 || currentFeature === null) continue;
    totalExtrusion += deposited;
    if (/support/iu.test(currentFeature)) supportExtrusion += deposited;
    if (
      !countedCurrentThinFeature &&
      /(?:thin\s*wall|gap\s*infill)/iu.test(currentFeature)
    ) {
      thinWallFeatureCount += 1;
      countedCurrentThinFeature = true;
    }
  }

  if (
    !Number.isFinite(totalExtrusion) ||
    totalExtrusion <= 0 ||
    !Number.isSafeInteger(thinWallFeatureCount)
  ) {
    throw new SlicingWorkerError(
      "deterministic_invalid",
      "INVALID_GEOMETRY",
      "Slicer artifact is missing normalized preflight metrics",
    );
  }
  return {
    thinWallFeatureCount,
    supportVolumeRatioPpm: Math.min(
      1_000_000,
      Math.max(0, Math.round((supportExtrusion / totalExtrusion) * 1_000_000)),
    ),
  };
}

function artifactSuffix(format: OrcaSliceRequest["artifactFormat"]): string {
  if (format === "gcode_3mf") return ".gcode.3mf";
  if (format === "bgcode") return ".bgcode";
  return ".gcode";
}

function assertSupportedArtifactFormat(
  format: OrcaSliceRequest["artifactFormat"],
): void {
  if (format === "bgcode") {
    throw new SlicingWorkerError(
      "unsupported_input",
      "UNSUPPORTED_FEATURE",
      "The pinned OrcaSlicer runtime cannot produce Prusa binary G-code",
    );
  }
}

function productionPlatePlan(
  input: OrcaSliceRequest,
): readonly number[] | null {
  const plan = input.copiesPerPlate;
  if (plan === undefined) return null;
  if (
    plan.length < 1 ||
    plan.some((copies) => !Number.isSafeInteger(copies) || copies < 1) ||
    plan.reduce((total, copies) => total + copies, 0) !== input.copies
  ) {
    throw new SlicingWorkerError(
      "deterministic_invalid",
      "INVALID_PROFILE",
      "Production plate plan does not match the accepted quantity",
    );
  }
  if (plan.length > 36) {
    throw new SlicingWorkerError(
      "unsupported_input",
      "UNSUPPORTED_FEATURE",
      "Pinned runtime supports at most 36 production plates per Job",
    );
  }
  if (input.artifactFormat !== "gcode_3mf" && plan.length > 1) {
    throw new SlicingWorkerError(
      "unsupported_input",
      "UNSUPPORTED_FEATURE",
      "Multi-plate production requires a G-code 3MF package",
    );
  }
  return plan;
}

function assemblyList(geometryPath: string, copiesPerPlate: readonly number[]) {
  return {
    plates: copiesPerPlate.map((count, index) => ({
      plate_name: `Plate ${index + 1}`,
      need_arrange: true,
      objects: [{ path: geometryPath, count, filaments: [1] }],
    })),
  };
}

function appendArtifactArguments(
  arguments_: string[],
  format: OrcaSliceRequest["artifactFormat"],
): void {
  assertSupportedArtifactFormat(format);
  if (format === "gcode_3mf") {
    arguments_.push("--export-3mf", "toolpath.gcode.3mf", "--min-save");
  }
}

async function partitionProfilePaths(
  profilePaths: readonly string[],
): Promise<ProfilePaths> {
  const result: ProfilePaths = { settings: [], filaments: [] };
  for (const profilePath of profilePaths) {
    let profile: unknown;
    try {
      profile = JSON.parse(await readFile(profilePath, "utf8"));
    } catch {
      throw new SlicingWorkerError(
        "deterministic_invalid",
        "INVALID_PROFILE",
        "Immutable slicer profile is not valid JSON",
      );
    }
    if (!profile || typeof profile !== "object" || Array.isArray(profile)) {
      throw new SlicingWorkerError(
        "deterministic_invalid",
        "INVALID_PROFILE",
        "Immutable slicer profile must be a JSON object",
      );
    }
    const value = profile as Record<string, unknown>;
    const target =
      value.type === "filament" || "filament_settings_id" in value
        ? result.filaments
        : result.settings;
    target.push(profilePath);
  }
  if (result.settings.length === 0) {
    throw new SlicingWorkerError(
      "deterministic_invalid",
      "INVALID_PROFILE",
      "At least one Orca machine or process settings profile is required",
    );
  }
  return result;
}

async function outputFiles(root: string, suffix: string): Promise<string[]> {
  const result: string[] = [];
  async function visit(directory: string): Promise<void> {
    for (const entry of await readdir(directory, { withFileTypes: true })) {
      const candidate = path.join(directory, entry.name);
      if (entry.isSymbolicLink()) {
        throw new SlicingWorkerError(
          "deterministic_invalid",
          "INVALID_GEOMETRY",
          "Slicer emitted an unsafe artifact",
        );
      }
      if (entry.isDirectory()) await visit(candidate);
      else if (entry.isFile() && entry.name.endsWith(suffix))
        result.push(candidate);
    }
  }
  await visit(root);
  return result.sort();
}

function sandboxPath(workspace: string, value: string): string {
  const relative = path.relative(workspace, value);
  if (relative.startsWith("..") || path.isAbsolute(relative)) {
    throw new Error("sandbox input is outside its workspace");
  }
  return path.posix.join("/work", ...relative.split(path.sep));
}

export class OrcaCliEngine implements OrcaEngine {
  constructor(
    private readonly config: EngineRuntimeConfig & {
      sandboxExecutable?: string;
      limitExecutable?: string;
    },
  ) {}

  async slice(input: OrcaSliceRequest): Promise<OrcaSliceOutput> {
    assertSupportedArtifactFormat(input.artifactFormat);
    const platePlan = productionPlatePlan(input);
    await mkdir(input.workspace, { recursive: true });
    const runDirectory = await mkdtemp(path.join(input.workspace, "run-"));
    const outputDirectory = path.join(runDirectory, "output");
    const temporaryDirectory = path.join(runDirectory, "tmp");
    await mkdir(outputDirectory, { recursive: true });
    await mkdir(temporaryDirectory, { recursive: true });
    const sandbox = this.config.sandboxExecutable ?? "/usr/bin/bwrap";
    const limiter = this.config.limitExecutable ?? "/usr/bin/prlimit";
    const profiles = await partitionProfilePaths(input.profilePaths);
    const settings = profiles.settings.map((profile) =>
      sandboxPath(input.workspace, profile),
    );
    const filaments = profiles.filaments.map((profile) =>
      sandboxPath(input.workspace, profile),
    );
    const orcaArguments = [
      "--debug",
      "2",
      "--slice",
      "0",
      "--outputdir",
      sandboxPath(input.workspace, outputDirectory),
      "--datadir",
      "/tmp/data",
      "--load-settings",
      settings.join(";"),
    ];
    if (filaments.length > 0) {
      orcaArguments.push("--load-filaments", filaments.join(";"));
    }
    if (platePlan && input.artifactFormat === "gcode_3mf") {
      const assemblyPath = path.join(runDirectory, "assembly.json");
      await writeFile(
        assemblyPath,
        JSON.stringify(
          assemblyList(
            sandboxPath(input.workspace, input.geometryPath),
            platePlan,
          ),
        ),
        { mode: 0o400 },
      );
      orcaArguments.push(
        "--load-assemble-list",
        sandboxPath(input.workspace, assemblyPath),
      );
    } else if (input.copies > 1) {
      orcaArguments.push(
        "--arrange",
        "1",
        "--clone-objects",
        String(input.copies),
      );
    }
    appendArtifactArguments(orcaArguments, input.artifactFormat);
    if (!(platePlan && input.artifactFormat === "gcode_3mf")) {
      orcaArguments.push(sandboxPath(input.workspace, input.geometryPath));
    }
    const arguments_ = [
      "--as=8589934592",
      "--cpu=1800",
      "--nproc=256",
      `--fsize=${this.config.maximumArtifactBytes}`,
      "--",
      sandbox,
      "--unshare-all",
      "--die-with-parent",
      "--new-session",
      "--tmpfs",
      "/",
      "--dir",
      "/opt",
      "--ro-bind",
      "/opt/orca",
      "/opt/orca",
      "--dir",
      "/usr",
      "--ro-bind",
      "/usr",
      "/usr",
      "--dir",
      "/lib",
      "--ro-bind-try",
      "/lib",
      "/lib",
      "--dir",
      "/lib64",
      "--ro-bind-try",
      "/lib64",
      "/lib64",
      "--dir",
      "/etc",
      "--dir",
      "/etc/fonts",
      "--ro-bind-try",
      "/etc/fonts",
      "/etc/fonts",
      "--dir",
      "/etc/ssl",
      "--ro-bind-try",
      "/etc/ssl/certs",
      "/etc/ssl/certs",
      "--symlink",
      "usr/bin",
      "/bin",
      "--symlink",
      "usr/sbin",
      "/sbin",
      "--dir",
      "/work",
      "--dir",
      "/tmp",
      "--bind",
      input.workspace,
      "/work",
      "--bind",
      temporaryDirectory,
      "/tmp",
      "--proc",
      "/proc",
      "--dev",
      "/dev",
      "--chdir",
      "/work",
      "--setenv",
      "HOME",
      "/tmp/home",
      "--setenv",
      "XDG_CACHE_HOME",
      "/tmp/cache",
      "--setenv",
      "XDG_CONFIG_HOME",
      "/tmp/config",
      "--setenv",
      "XDG_DATA_HOME",
      "/tmp/data",
      "--setenv",
      "LC_ALL",
      "C",
      this.config.executable,
      ...orcaArguments,
    ];
    await this.execute(limiter, arguments_, input.workspace);
    const files = await outputFiles(
      outputDirectory,
      artifactSuffix(input.artifactFormat),
    );
    if (files.length !== 1) {
      throw new SlicingWorkerError(
        "deterministic_invalid",
        "INVALID_GEOMETRY",
        "Slicer did not emit exactly one bounded artifact",
      );
    }
    const artifactBytes = await readFile(files[0]!);
    if (artifactBytes.byteLength > this.config.maximumArtifactBytes) {
      throw new SlicingWorkerError(
        "deterministic_invalid",
        "RESOURCE_LIMIT_EXCEEDED",
        "Slicer artifact exceeds the configured byte limit",
      );
    }
    const metrics =
      input.requireMetrics === false
        ? validatedProductionMetrics(
            artifactBytes,
            input,
            platePlan,
            this.config,
          )
        : input.artifactFormat === "gcode"
          ? parseOrcaArtifact(artifactBytes, this.config.version)
          : (() => {
              throw new SlicingWorkerError(
                "unsupported_input",
                "UNSUPPORTED_FEATURE",
                "Pinned runtime cannot read metrics from this artifact format",
              );
            })();
    return {
      ...metrics,
      artifactBytes,
    };
  }

  private async execute(
    executable: string,
    arguments_: readonly string[],
    cwd: string,
  ): Promise<void> {
    await new Promise<void>((resolve, reject) => {
      const child = spawn(executable, arguments_, {
        cwd,
        stdio: ["ignore", "pipe", "pipe"],
        env: {
          HOME: "/tmp",
          LANG: "C",
          LC_ALL: "C",
          PATH: "/usr/bin:/bin",
        },
      });
      let diagnostics = 0;
      let overflow = false;
      let timedOut = false;
      const observe = (chunk: Buffer) => {
        diagnostics += chunk.byteLength;
        if (diagnostics > this.config.maximumDiagnosticBytes) {
          overflow = true;
          child.kill("SIGKILL");
        }
      };
      child.stdout.on("data", observe);
      child.stderr.on("data", observe);
      const timeout = setTimeout(() => {
        timedOut = true;
        child.kill("SIGKILL");
      }, this.config.timeoutMilliseconds);
      child.once("error", () => {
        clearTimeout(timeout);
        reject(
          new SlicingWorkerError(
            "retryable_infrastructure",
            "ENGINE_UNAVAILABLE",
            "Pinned slicing engine could not be started",
            5_000,
          ),
        );
      });
      child.once("close", (code, signal) => {
        clearTimeout(timeout);
        if (overflow) {
          reject(
            new SlicingWorkerError(
              "deterministic_invalid",
              "RESOURCE_LIMIT_EXCEEDED",
              "Slicer diagnostics exceeded the configured byte limit",
            ),
          );
        } else if (timedOut) {
          reject(
            new SlicingWorkerError(
              "retryable_infrastructure",
              "ENGINE_TIMEOUT",
              "Pinned slicing engine exceeded its execution deadline",
              30_000,
            ),
          );
        } else if (signal !== null) {
          reject(
            new SlicingWorkerError(
              "deterministic_invalid",
              "RESOURCE_LIMIT_EXCEEDED",
              "Pinned slicing engine exceeded a process resource limit",
            ),
          );
        } else if (code !== 0) {
          reject(
            new SlicingWorkerError(
              "deterministic_invalid",
              "INVALID_GEOMETRY",
              "Pinned slicing engine rejected the canonical geometry",
            ),
          );
        } else {
          resolve();
        }
      });
    });
  }
}

export class OrcaSidecarEngine implements OrcaEngine {
  constructor(
    private readonly config: EngineRuntimeConfig,
    private readonly runnerRoot: string,
  ) {}

  async slice(input: OrcaSliceRequest): Promise<OrcaSliceOutput> {
    assertSupportedArtifactFormat(input.artifactFormat);
    const platePlan = productionPlatePlan(input);
    const profiles = await partitionProfilePaths(input.profilePaths);
    await mkdir(this.runnerRoot, { recursive: true });
    const requestDirectory = await mkdtemp(
      path.join(this.runnerRoot, "request-"),
    );
    let runnerOwnsCleanup = false;
    try {
      await mkdir(path.join(requestDirectory, "output"), {
        recursive: true,
        mode: 0o700,
      });
      await mkdir(path.join(requestDirectory, "tmp", "data"), {
        recursive: true,
        mode: 0o700,
      });
      await writeFile(
        path.join(requestDirectory, "lease-expires-at"),
        `${Math.ceil(
          (Date.now() + this.config.timeoutMilliseconds + 60_000) / 1_000,
        )}\n`,
        { mode: 0o400 },
      );
      const profileDirectory = path.join(requestDirectory, "profiles");
      const settingsDirectory = path.join(profileDirectory, "settings");
      const filamentsDirectory = path.join(profileDirectory, "filaments");
      await mkdir(settingsDirectory, { recursive: true });
      await mkdir(filamentsDirectory, { recursive: true });
      await copyFile(
        input.geometryPath,
        path.join(requestDirectory, "geometry.stl"),
      );
      for (const [index, profile] of profiles.settings.entries()) {
        await copyFile(profile, path.join(settingsDirectory, `${index}.json`));
      }
      for (const [index, profile] of profiles.filaments.entries()) {
        await copyFile(profile, path.join(filamentsDirectory, `${index}.json`));
      }
      await writeFile(
        path.join(requestDirectory, "copies"),
        `${input.copies}\n`,
      );
      await writeFile(
        path.join(requestDirectory, "artifact-format"),
        `${input.artifactFormat}\n`,
      );
      if (platePlan && input.artifactFormat === "gcode_3mf") {
        await writeFile(
          path.join(requestDirectory, "assembly.json"),
          JSON.stringify(assemblyList("/work/geometry.stl", platePlan)),
        );
      }
      await writeFile(
        path.join(requestDirectory, "timeout-seconds"),
        `${Math.ceil(this.config.timeoutMilliseconds / 1_000)}\n`,
      );
      const preparing = path.join(requestDirectory, "preparing");
      await writeFile(preparing, "ready\n");
      await rename(preparing, path.join(requestDirectory, "ready"));

      const deadline = Date.now() + this.config.timeoutMilliseconds + 10_000;
      while (Date.now() < deadline) {
        if (await exists(path.join(requestDirectory, "complete"))) {
          return this.readResult(requestDirectory, input, platePlan);
        }
        if (await exists(path.join(requestDirectory, "failed"))) {
          throw await this.runnerFailure(requestDirectory);
        }
        await new Promise((resolve) => setTimeout(resolve, 100));
      }
      await writeFile(path.join(requestDirectory, "cancel"), "cancel\n");
      runnerOwnsCleanup = await exists(
        path.join(requestDirectory, "processing"),
      );
      throw new SlicingWorkerError(
        "retryable_infrastructure",
        "ENGINE_TIMEOUT",
        "Pinned slicing engine sidecar exceeded its execution deadline",
        30_000,
      );
    } finally {
      if (!runnerOwnsCleanup) {
        await rm(requestDirectory, { recursive: true, force: true });
      }
    }
  }

  private async runnerFailure(
    requestDirectory: string,
  ): Promise<SlicingWorkerError> {
    const code = (
      await readFile(path.join(requestDirectory, "failure-code"), "utf8")
    ).trim();
    if (code === "ENGINE_TIMEOUT") {
      return new SlicingWorkerError(
        "retryable_infrastructure",
        "ENGINE_TIMEOUT",
        "Pinned slicing engine exceeded its execution deadline",
        30_000,
      );
    }
    if (code === "ENGINE_UNAVAILABLE") {
      return new SlicingWorkerError(
        "retryable_infrastructure",
        "ENGINE_UNAVAILABLE",
        "Pinned slicing engine could not complete the request",
        5_000,
      );
    }
    if (code === "RESOURCE_LIMIT_EXCEEDED") {
      return new SlicingWorkerError(
        "deterministic_invalid",
        "RESOURCE_LIMIT_EXCEEDED",
        "Pinned slicing engine exceeded a process resource limit",
      );
    }
    if (code === "INVALID_PROFILE") {
      return new SlicingWorkerError(
        "deterministic_invalid",
        "INVALID_PROFILE",
        "Pinned slicing profile could not be loaded",
      );
    }
    return new SlicingWorkerError(
      "deterministic_invalid",
      "INVALID_GEOMETRY",
      "Pinned slicing engine rejected the canonical geometry",
    );
  }

  private async readResult(
    requestDirectory: string,
    input: OrcaSliceRequest,
    platePlan: readonly number[] | null,
  ): Promise<OrcaSliceOutput> {
    const files = await outputFiles(
      path.join(requestDirectory, "output"),
      artifactSuffix(input.artifactFormat),
    );
    if (files.length !== 1) {
      throw new SlicingWorkerError(
        "deterministic_invalid",
        "INVALID_GEOMETRY",
        "Slicer sidecar did not emit exactly one bounded artifact",
      );
    }
    const artifactBytes = await readFile(files[0]!);
    if (artifactBytes.byteLength > this.config.maximumArtifactBytes) {
      throw new SlicingWorkerError(
        "deterministic_invalid",
        "RESOURCE_LIMIT_EXCEEDED",
        "Slicer artifact exceeds the configured byte limit",
      );
    }
    const metrics =
      input.requireMetrics === false
        ? validatedProductionMetrics(
            artifactBytes,
            input,
            platePlan,
            this.config,
          )
        : input.artifactFormat === "gcode"
          ? parseOrcaArtifact(artifactBytes, this.config.version)
          : (() => {
              throw new SlicingWorkerError(
                "unsupported_input",
                "UNSUPPORTED_FEATURE",
                "Pinned runtime cannot read metrics from this artifact format",
              );
            })();
    return { ...metrics, artifactBytes };
  }
}

async function exists(candidate: string): Promise<boolean> {
  try {
    await access(candidate);
    return true;
  } catch {
    return false;
  }
}
