import {
  mkdtemp,
  mkdir,
  readFile,
  readdir,
  rm,
  writeFile,
} from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";
import { afterEach, describe, expect, it } from "vitest";
import { OrcaSidecarEngine } from "./orca-engine.js";

const cleanup: string[] = [];

afterEach(async () => {
  await Promise.all(
    cleanup
      .splice(0)
      .map((directory) => rm(directory, { recursive: true, force: true })),
  );
});

describe("Orca sidecar protocol", () => {
  it("rejects bgcode explicitly when the pinned engine cannot produce it", async () => {
    const engine = new OrcaSidecarEngine(
      {
        executable: "/opt/orca/AppRun",
        name: "orcaslicer",
        version: "2.4.2",
        imageSha256: "b".repeat(64),
        timeoutMilliseconds: 1_000,
        runnerRoot: "/unused",
        maximumArtifactBytes: 1024,
        maximumDiagnosticBytes: 1024,
      },
      "/unused",
    );
    await expect(
      engine.slice({
        workspace: "/unused",
        geometryPath: "/unused/geometry.stl",
        profilePaths: [],
        copies: 1,
        artifactFormat: "bgcode",
        requireMetrics: false,
      }),
    ).rejects.toMatchObject({
      failureClass: "unsupported_input",
      code: "UNSUPPORTED_FEATURE",
    });
  });

  it("exchanges only bounded workspace files and removes the request", async () => {
    const root = await mkdtemp(path.join(tmpdir(), "taven-runner-test-"));
    const workspace = await mkdtemp(path.join(tmpdir(), "taven-engine-test-"));
    cleanup.push(root, workspace);
    const geometryPath = path.join(workspace, "geometry.stl");
    const profilePath = path.join(workspace, `${"a".repeat(64)}.json`);
    const filamentPath = path.join(workspace, `${"b".repeat(64)}.json`);
    await writeFile(geometryPath, "solid fixture\nendsolid fixture\n");
    await writeFile(profilePath, "{}\n");
    await writeFile(filamentPath, '{"type":"filament"}\n');
    const fakeRunner = (async () => {
      for (;;) {
        const requestName = (await readdir(root)).find((name) =>
          name.startsWith("request-"),
        );
        if (!requestName) {
          await new Promise((resolve) => setTimeout(resolve, 5));
          continue;
        }
        const request = path.join(root, requestName);
        try {
          await readFile(path.join(request, "ready"));
        } catch {
          await new Promise((resolve) => setTimeout(resolve, 5));
          continue;
        }
        expect(await readFile(path.join(request, "copies"), "utf8")).toBe(
          "2\n",
        );
        expect(
          await readdir(path.join(request, "profiles", "settings")),
        ).toEqual(["0.json"]);
        expect(
          await readdir(path.join(request, "profiles", "filaments")),
        ).toEqual(["0.json"]);
        await mkdir(path.join(request, "output"));
        await writeFile(
          path.join(request, "output", "fixture.gcode"),
          "; generated by OrcaSlicer 2.4.2 on 2026-08-31 at 12:00:00\n; total estimated time: 2m 0s\n; filament used [g] = 2\n",
        );
        await writeFile(path.join(request, "complete"), "\n");
        return;
      }
    })();
    const engine = new OrcaSidecarEngine(
      {
        executable: "/opt/orca/AppRun",
        name: "orcaslicer",
        version: "2.4.2",
        imageSha256: "b".repeat(64),
        timeoutMilliseconds: 1_000,
        runnerRoot: root,
        maximumArtifactBytes: 1024,
        maximumDiagnosticBytes: 1024,
      },
      root,
    );
    await expect(
      engine.slice({
        workspace,
        geometryPath,
        profilePaths: [profilePath, filamentPath],
        copies: 2,
        artifactFormat: "gcode",
      }),
    ).resolves.toMatchObject({
      estimatedPrintSeconds: 120n,
      estimatedMaterialMilligrams: 2_000n,
    });
    await fakeRunner;
    expect(await readdir(root)).toEqual([]);
  });

  it("writes an ordered Orca assembly list for a multi-plate package", async () => {
    const root = await mkdtemp(path.join(tmpdir(), "taven-runner-test-"));
    const workspace = await mkdtemp(path.join(tmpdir(), "taven-engine-test-"));
    cleanup.push(root, workspace);
    const geometryPath = path.join(workspace, "geometry.stl");
    const profilePath = path.join(workspace, "machine.json");
    await writeFile(geometryPath, "solid fixture\nendsolid fixture\n");
    await writeFile(profilePath, "{}\n");
    const fakeRunner = (async () => {
      for (;;) {
        const requestName = (await readdir(root)).find((name) =>
          name.startsWith("request-"),
        );
        if (!requestName) {
          await new Promise((resolve) => setTimeout(resolve, 5));
          continue;
        }
        const request = path.join(root, requestName);
        try {
          await readFile(path.join(request, "ready"));
        } catch {
          await new Promise((resolve) => setTimeout(resolve, 5));
          continue;
        }
        const assembly = JSON.parse(
          await readFile(path.join(request, "assembly.json"), "utf8"),
        ) as {
          plates: Array<{
            plate_name: string;
            need_arrange: boolean;
            objects: Array<{
              path: string;
              count: number;
              filaments: number[];
            }>;
          }>;
        };
        expect(assembly.plates).toEqual(
          [2, 2, 1].map((count, index) => ({
            plate_name: `Plate ${index + 1}`,
            need_arrange: true,
            objects: [
              {
                path: path.join(request, "geometry.stl"),
                count,
                filaments: [1],
              },
            ],
          })),
        );
        await mkdir(path.join(request, "output"));
        await writeFile(
          path.join(request, "output", "fixture.gcode.3mf"),
          "bounded package",
        );
        await writeFile(path.join(request, "complete"), "\n");
        return;
      }
    })();
    const engine = new OrcaSidecarEngine(
      {
        executable: "/opt/orca/AppRun",
        name: "orcaslicer",
        version: "2.4.2",
        imageSha256: "b".repeat(64),
        timeoutMilliseconds: 1_000,
        runnerRoot: root,
        maximumArtifactBytes: 1024,
        maximumDiagnosticBytes: 1024,
      },
      root,
    );

    await expect(
      engine.slice({
        workspace,
        geometryPath,
        profilePaths: [profilePath],
        copies: 5,
        copiesPerPlate: [2, 2, 1],
        artifactFormat: "gcode_3mf",
        requireMetrics: false,
      }),
    ).resolves.toMatchObject({ artifactBytes: expect.any(Uint8Array) });
    await fakeRunner;
    expect(await readdir(root)).toEqual([]);
  });
});
