import { createHash } from "node:crypto";
import {
  mkdtemp,
  mkdir,
  readFile,
  readdir,
  rm,
  stat,
  writeFile,
} from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";
import { afterEach, describe, expect, it, vi } from "vitest";
import {
  OrcaSidecarEngine,
  parseOrcaArtifact,
  validateProductionArtifact,
} from "./orca-engine.js";

const cleanup: string[] = [];

function storedZip(entries: Readonly<Record<string, string>>): Uint8Array {
  const local: Buffer[] = [];
  const central: Buffer[] = [];
  let offset = 0;
  for (const [name, value] of Object.entries(entries)) {
    const nameBytes = Buffer.from(name);
    const contents = Buffer.from(value);
    const localHeader = Buffer.alloc(30);
    localHeader.writeUInt32LE(0x04034b50, 0);
    localHeader.writeUInt16LE(20, 4);
    localHeader.writeUInt32LE(contents.byteLength, 18);
    localHeader.writeUInt32LE(contents.byteLength, 22);
    localHeader.writeUInt16LE(nameBytes.byteLength, 26);
    const centralHeader = Buffer.alloc(46);
    centralHeader.writeUInt32LE(0x02014b50, 0);
    centralHeader.writeUInt16LE(20, 4);
    centralHeader.writeUInt16LE(20, 6);
    centralHeader.writeUInt32LE(contents.byteLength, 20);
    centralHeader.writeUInt32LE(contents.byteLength, 24);
    centralHeader.writeUInt16LE(nameBytes.byteLength, 28);
    centralHeader.writeUInt32LE(offset, 42);
    local.push(localHeader, nameBytes, contents);
    central.push(centralHeader, nameBytes);
    offset +=
      localHeader.byteLength + nameBytes.byteLength + contents.byteLength;
  }
  const centralBytes = Buffer.concat(central);
  const end = Buffer.alloc(22);
  end.writeUInt32LE(0x06054b50, 0);
  end.writeUInt16LE(Object.keys(entries).length, 8);
  end.writeUInt16LE(Object.keys(entries).length, 10);
  end.writeUInt32LE(centralBytes.byteLength, 12);
  end.writeUInt32LE(offset, 16);
  return Buffer.concat([...local, centralBytes, end]);
}

const validGcode =
  "; generated by OrcaSlicer 2.4.2 on 2026-08-31 at 12:00:00\n; total estimated time: 2m 0s\n; filament used [g] = 2\n; EXECUTABLE_BLOCK_START\nM83\n; CHANGE_LAYER\n; FEATURE: Outer wall\nG1 X1 E3\n; FEATURE: Support\nG1 X2 E1\nM104 S0\n; EXECUTABLE_BLOCK_END\n";
const incompleteGcode =
  "; generated by OrcaSlicer 2.4.2 on 2026-08-31 at 12:00:00\n; total estimated time: 2m 0s\n; filament used [g] = 2\n; EXECUTABLE_BLOCK_START\nM83\n; CHANGE_LAYER\n; FEATURE: Outer wall\nG1 X1 E3\n";

function productionPackage(
  plateCount: number,
  digestOverride?: string,
): Uint8Array {
  const entries: Record<string, string> = {
    "Metadata/slice_info.config": "<config/>\n",
  };
  for (let plate = 1; plate <= plateCount; plate += 1) {
    const name = `Metadata/plate_${plate}.gcode`;
    entries[name] = validGcode;
    entries[`${name}.md5`] =
      digestOverride ??
      createHash("md5").update(validGcode).digest("hex").toUpperCase();
  }
  return storedZip(entries);
}

async function expectProducerOwnedDirectories(request: string): Promise<void> {
  const expectedUid = process.getuid?.();
  const expectedGid = process.getgid?.();
  for (const relative of [
    "output",
    "tmp",
    "tmp/data",
    "profiles",
    "profiles/settings",
    "profiles/filaments",
  ]) {
    const metadata = await stat(path.join(request, relative));
    expect(metadata.isDirectory()).toBe(true);
    if (expectedUid !== undefined) expect(metadata.uid).toBe(expectedUid);
    if (expectedGid !== undefined) expect(metadata.gid).toBe(expectedGid);
    expect(metadata.mode & 0o777).toBe(0o770);
  }
  expect((await stat(request)).mode & 0o777).toBe(0o770);
  expect(
    (await stat(path.join(request, "lease-expires-at"))).mode & 0o777,
  ).toBe(0o440);
  for (const relative of ["profiles/settings", "profiles/filaments"]) {
    for (const profile of await readdir(path.join(request, relative))) {
      expect(
        (await stat(path.join(request, relative, profile))).mode & 0o777,
      ).toBe(0o400);
    }
  }
}

afterEach(async () => {
  vi.restoreAllMocks();
  await Promise.all(
    cleanup
      .splice(0)
      .map((directory) => rm(directory, { recursive: true, force: true })),
  );
});

describe("Orca sidecar protocol", () => {
  it("validates plain and packaged production artifacts", () => {
    expect(() =>
      validateProductionArtifact(
        new TextEncoder().encode(validGcode),
        "gcode",
        1,
        "2.4.2",
        1024 * 1024,
      ),
    ).not.toThrow();
    expect(() =>
      validateProductionArtifact(
        new Uint8Array(),
        "gcode",
        1,
        "2.4.2",
        1024 * 1024,
      ),
    ).toThrow();
    expect(() =>
      validateProductionArtifact(
        new TextEncoder().encode(incompleteGcode),
        "gcode",
        1,
        "2.4.2",
        1024 * 1024,
      ),
    ).toThrow(/complete executable program/u);
    const incompletePackage = storedZip({
      "Metadata/slice_info.config": "<config/>\n",
      "Metadata/plate_1.gcode": incompleteGcode,
      "Metadata/plate_1.gcode.md5": createHash("md5")
        .update(incompleteGcode)
        .digest("hex")
        .toUpperCase(),
    });
    expect(() =>
      validateProductionArtifact(
        incompletePackage,
        "gcode_3mf",
        1,
        "2.4.2",
        1024 * 1024,
      ),
    ).toThrow(/complete executable program/u);
    expect(() =>
      validateProductionArtifact(
        productionPackage(2),
        "gcode_3mf",
        2,
        "2.4.2",
        1024 * 1024,
      ),
    ).not.toThrow();
    expect(() =>
      validateProductionArtifact(
        productionPackage(2),
        "gcode_3mf",
        1,
        "2.4.2",
        1024 * 1024,
      ),
    ).toThrow(/plate count/u);
    expect(() =>
      validateProductionArtifact(
        productionPackage(1, "0".repeat(32)),
        "gcode_3mf",
        1,
        "2.4.2",
        1024 * 1024,
      ),
    ).toThrow(/checksum/u);
  });

  it("derives support ratio and thin-wall findings from normalized feature extrusion", () => {
    const metrics = parseOrcaArtifact(
      new TextEncoder().encode(
        "; generated by OrcaSlicer 2.4.2 on 2026-08-31 at 12:00:00\n; total estimated time: 2m 0s\n; filament used [g] = 2\nM83\n; FEATURE: Outer wall\nG1 X1 E3\nG1 E-.5\nG1 E.5\n; FEATURE: Support\nG1 X2 E1\n; FEATURE: Support interface\nG1 X3 E1\n; FEATURE: Gap infill\nG1 X4 E1\n",
      ),
      "2.4.2",
    );

    expect(metrics).toEqual({
      estimatedPrintSeconds: 120n,
      estimatedMaterialMilligrams: 2_000n,
      thinWallFeatureCount: 1,
      supportVolumeRatioPpm: 333_333,
    });
  });

  it("rejects artifacts that omit slicer preflight feature metrics", () => {
    expect(() =>
      parseOrcaArtifact(
        new TextEncoder().encode(
          "; generated by OrcaSlicer 2.4.2 on 2026-08-31 at 12:00:00\n; total estimated time: 2m 0s\n; filament used [g] = 2\n",
        ),
        "2.4.2",
      ),
    ).toThrow(/preflight metrics/u);
  });

  it("rejects bgcode explicitly when the pinned engine cannot produce it", async () => {
    const engine = new OrcaSidecarEngine(
      {
        executable: "/opt/orca/AppRun",
        name: "orcaslicer",
        version: "2.4.2",
        imageSha256: "b".repeat(64),
        timeoutMilliseconds: 1_000,
        runnerRoot: "/unused",
        maximumArtifactBytes: 1024,
        maximumDiagnosticBytes: 1024,
      },
      "/unused",
    );
    await expect(
      engine.slice({
        workspace: "/unused",
        geometryPath: "/unused/geometry.stl",
        profilePaths: [],
        copies: 1,
        artifactFormat: "bgcode",
        requireMetrics: false,
      }),
    ).rejects.toMatchObject({
      failureClass: "unsupported_input",
      code: "UNSUPPORTED_FEATURE",
    });
  });

  it("exchanges only bounded workspace files and removes the request", async () => {
    const root = await mkdtemp(path.join(tmpdir(), "taven-runner-test-"));
    const workspace = await mkdtemp(path.join(tmpdir(), "taven-engine-test-"));
    cleanup.push(root, workspace);
    const geometryPath = path.join(workspace, "geometry.stl");
    const profilePath = path.join(workspace, `${"a".repeat(64)}.json`);
    const filamentPath = path.join(workspace, `${"b".repeat(64)}.json`);
    await writeFile(geometryPath, "solid fixture\nendsolid fixture\n");
    await writeFile(profilePath, "{}\n");
    await writeFile(filamentPath, '{"type":"filament"}\n');
    const fakeRunner = (async () => {
      for (;;) {
        const requestName = (await readdir(root)).find((name) =>
          name.startsWith("request-"),
        );
        if (!requestName) {
          await new Promise((resolve) => setTimeout(resolve, 5));
          continue;
        }
        const request = path.join(root, requestName);
        try {
          await readFile(path.join(request, "ready"));
        } catch {
          await new Promise((resolve) => setTimeout(resolve, 5));
          continue;
        }
        expect(await readFile(path.join(request, "copies"), "utf8")).toBe(
          "2\n",
        );
        expect(
          Number(
            (
              await readFile(path.join(request, "lease-expires-at"), "utf8")
            ).trim(),
          ),
        ).toBeGreaterThan(Math.floor(Date.now() / 1_000));
        expect(
          await readdir(path.join(request, "profiles", "settings")),
        ).toEqual(["0.json"]);
        expect(
          await readdir(path.join(request, "profiles", "filaments")),
        ).toEqual(["0.json"]);
        await expectProducerOwnedDirectories(request);
        await writeFile(
          path.join(request, "output", "fixture.gcode"),
          "; generated by OrcaSlicer 2.4.2 on 2026-08-31 at 12:00:00\n; total estimated time: 2m 0s\n; filament used [g] = 2\nM83\n; FEATURE: Outer wall\nG1 X1 E3\n; FEATURE: Support\nG1 X2 E1\n",
        );
        await writeFile(path.join(request, "complete"), "\n");
        return;
      }
    })();
    const engine = new OrcaSidecarEngine(
      {
        executable: "/opt/orca/AppRun",
        name: "orcaslicer",
        version: "2.4.2",
        imageSha256: "b".repeat(64),
        timeoutMilliseconds: 1_000,
        runnerRoot: root,
        maximumArtifactBytes: 1024,
        maximumDiagnosticBytes: 1024,
      },
      root,
    );
    await expect(
      engine.slice({
        workspace,
        geometryPath,
        profilePaths: [profilePath, filamentPath],
        copies: 2,
        artifactFormat: "gcode",
      }),
    ).resolves.toMatchObject({
      estimatedPrintSeconds: 120n,
      estimatedMaterialMilligrams: 2_000n,
      thinWallFeatureCount: 0,
      supportVolumeRatioPpm: 250_000,
    });
    await fakeRunner;
    expect(await readdir(root)).toEqual([]);
  });

  it("writes an ordered Orca assembly list for a multi-plate package", async () => {
    const root = await mkdtemp(path.join(tmpdir(), "taven-runner-test-"));
    const workspace = await mkdtemp(path.join(tmpdir(), "taven-engine-test-"));
    cleanup.push(root, workspace);
    const geometryPath = path.join(workspace, "geometry.stl");
    const profilePath = path.join(workspace, "machine.json");
    await writeFile(geometryPath, "solid fixture\nendsolid fixture\n");
    await writeFile(profilePath, "{}\n");
    const fakeRunner = (async () => {
      for (;;) {
        const requestName = (await readdir(root)).find((name) =>
          name.startsWith("request-"),
        );
        if (!requestName) {
          await new Promise((resolve) => setTimeout(resolve, 5));
          continue;
        }
        const request = path.join(root, requestName);
        try {
          await readFile(path.join(request, "ready"));
        } catch {
          await new Promise((resolve) => setTimeout(resolve, 5));
          continue;
        }
        const assembly = JSON.parse(
          await readFile(path.join(request, "assembly.json"), "utf8"),
        ) as {
          plates: Array<{
            plate_name: string;
            need_arrange: boolean;
            objects: Array<{
              path: string;
              count: number;
              filaments: number[];
            }>;
          }>;
        };
        expect(assembly.plates).toEqual(
          [2, 2, 1].map((count, index) => ({
            plate_name: `Plate ${index + 1}`,
            need_arrange: true,
            objects: [
              {
                path: "/work/geometry.stl",
                count,
                filaments: [1],
              },
            ],
          })),
        );
        await expectProducerOwnedDirectories(request);
        await writeFile(
          path.join(request, "output", "fixture.gcode.3mf"),
          productionPackage(3),
        );
        await writeFile(path.join(request, "complete"), "\n");
        return;
      }
    })();
    const engine = new OrcaSidecarEngine(
      {
        executable: "/opt/orca/AppRun",
        name: "orcaslicer",
        version: "2.4.2",
        imageSha256: "b".repeat(64),
        timeoutMilliseconds: 1_000,
        runnerRoot: root,
        maximumArtifactBytes: 10 * 1024,
        maximumDiagnosticBytes: 1024,
      },
      root,
    );

    await expect(
      engine.slice({
        workspace,
        geometryPath,
        profilePaths: [profilePath],
        copies: 5,
        copiesPerPlate: [2, 2, 1],
        artifactFormat: "gcode_3mf",
        requireMetrics: false,
      }),
    ).resolves.toMatchObject({ artifactBytes: expect.any(Uint8Array) });
    await fakeRunner;
    expect(await readdir(root)).toEqual([]);
  });

  it("logs a bounded sanitized sidecar diagnostic without exposing it in the result", async () => {
    const root = await mkdtemp(path.join(tmpdir(), "taven-runner-test-"));
    const workspace = await mkdtemp(path.join(tmpdir(), "taven-engine-test-"));
    cleanup.push(root, workspace);
    const geometryPath = path.join(workspace, "geometry.stl");
    const profilePath = path.join(workspace, "machine.json");
    await writeFile(geometryPath, "solid fixture\nendsolid fixture\n");
    await writeFile(profilePath, "{}\n");
    const fakeRunner = (async () => {
      for (;;) {
        const requestName = (await readdir(root)).find((name) =>
          name.startsWith("request-"),
        );
        if (!requestName) {
          await new Promise((resolve) => setTimeout(resolve, 5));
          continue;
        }
        const request = path.join(root, requestName);
        try {
          await readFile(path.join(request, "ready"));
        } catch {
          await new Promise((resolve) => setTimeout(resolve, 5));
          continue;
        }
        await writeFile(path.join(request, "engine-return-code"), "-5\n");
        await writeFile(
          path.join(request, "diagnostics"),
          "failed reading /tmp/secret-token from engine\u0000",
        );
        await writeFile(
          path.join(request, "failure-code"),
          "INVALID_PROFILE\n",
        );
        await writeFile(path.join(request, "failed"), "\n");
        return;
      }
    })();
    const warning = vi
      .spyOn(console, "warn")
      .mockImplementation(() => undefined);
    const engine = new OrcaSidecarEngine(
      {
        executable: "/opt/orca/AppRun",
        name: "orcaslicer",
        version: "2.4.2",
        imageSha256: "b".repeat(64),
        timeoutMilliseconds: 1_000,
        runnerRoot: root,
        maximumArtifactBytes: 1024,
        maximumDiagnosticBytes: 16,
      },
      root,
    );

    await expect(
      engine.slice({
        workspace,
        geometryPath,
        profilePaths: [profilePath],
        copies: 1,
        artifactFormat: "gcode",
      }),
    ).rejects.toMatchObject({
      code: "INVALID_PROFILE",
      message: "Pinned slicing profile could not be loaded",
    });
    await fakeRunner;
    expect(warning).toHaveBeenCalledWith(
      expect.stringContaining("INVALID_PROFILE (return code -5)"),
    );
    const message = warning.mock.calls[0]?.[0] as string;
    expect(message).not.toContain("/tmp/secret-token");
    expect(message.length).toBeLessThanOrEqual(512 + 96);
    expect(await readdir(root)).toEqual([]);
  });

  it("preserves deterministic invalid geometry reported by the runner", async () => {
    const root = await mkdtemp(path.join(tmpdir(), "taven-runner-test-"));
    cleanup.push(root);
    const request = path.join(root, "request-failed");
    await mkdir(request);
    await writeFile(path.join(request, "failure-code"), "INVALID_GEOMETRY\n");
    const engine = new OrcaSidecarEngine(
      {
        executable: "/opt/orca/AppRun",
        name: "orcaslicer",
        version: "2.4.2",
        imageSha256: "b".repeat(64),
        timeoutMilliseconds: 1_000,
        runnerRoot: root,
        maximumArtifactBytes: 1024,
        maximumDiagnosticBytes: 1024,
      },
      root,
    ) as unknown as {
      runnerFailure(requestDirectory: string): Promise<unknown>;
    };

    await expect(engine.runnerFailure(request)).resolves.toMatchObject({
      failureClass: "deterministic_invalid",
      code: "INVALID_GEOMETRY",
    });
  });
});
