import { readFile } from "node:fs/promises";
import path from "node:path";
import {
  geometrySelectionSha256,
  machineOccupancyCacheIdentitySha256,
  slicingInputFingerprint,
  type SlicingJob,
  type SlicingJobKind,
} from "@taven/slicer-contracts";
import { describe, expect, it } from "vitest";
import type { WorkerConfig } from "./config.js";
import { sha256, type WorkerObjectStore } from "./object-store.js";
import type { OrcaEngine, OrcaSliceRequest } from "./orca-engine.js";
import { SlicingProcessor } from "./processor.js";

const ids = {
  source: "00000000-0000-4000-8000-000000000001",
  geometry: "00000000-0000-4000-8000-000000000002",
  job: "00000000-0000-4000-8000-000000000003",
  correlation: "00000000-0000-4000-8000-000000000004",
  machine: "00000000-0000-4000-8000-000000000005",
  machineProfile: "00000000-0000-4000-8000-000000000006",
  calibration: "00000000-0000-4000-8000-000000000007",
  printConfig: "00000000-0000-4000-8000-000000000008",
  arrangement: "00000000-0000-4000-8000-000000000009",
  shipment: "00000000-0000-4000-8000-000000000010",
};

class MemoryStore implements WorkerObjectStore {
  readonly objects = new Map<string, Uint8Array>();
  readonly writes: string[] = [];

  async read(key: string, maximum: number, expected?: string) {
    const bytes = this.objects.get(key);
    if (!bytes) return null;
    if (bytes.byteLength > maximum) throw new Error("too large");
    const digest = sha256(bytes);
    if (expected && expected !== digest) throw new Error("checksum mismatch");
    return { bytes, sha256: digest };
  }

  async write(key: string, bytes: Uint8Array) {
    const existing = this.objects.get(key);
    if (existing && sha256(existing) !== sha256(bytes))
      throw new Error("conflict");
    this.objects.set(key, new Uint8Array(bytes));
    this.writes.push(key);
    return { sha256: sha256(bytes), cacheHit: existing !== undefined };
  }

  async delete(key: string) {
    this.objects.delete(key);
  }
}

class FakeEngine implements OrcaEngine {
  readonly calls: OrcaSliceRequest[] = [];

  async slice(input: OrcaSliceRequest) {
    this.calls.push(input);
    return {
      estimatedPrintSeconds: BigInt(input.copies * 60),
      estimatedMaterialMilligrams: BigInt(input.copies * 1_000),
      artifactBytes: new TextEncoder().encode(
        `; generated by OrcaSlicer 2.4.2 on 2026-08-31 at 12:00:00\n; total estimated time: ${input.copies}m 0s\n; filament used [g] = ${input.copies}\n`,
      ),
    };
  }
}

const config: Pick<WorkerConfig, "engine" | "limits"> = {
  engine: {
    executable: "/opt/orca/AppRun",
    name: "orcaslicer",
    version: "2.4.2",
    imageSha256: "a".repeat(64),
    timeoutMilliseconds: 1_000,
    runnerRoot: null,
  },
  limits: {
    sourceBytes: 10 * 1024 * 1024,
    artifactBytes: 10 * 1024 * 1024,
    diagnosticBytes: 1024,
  },
};

function envelope<K extends SlicingJobKind>(kind: K, input: unknown) {
  const fingerprint = slicingInputFingerprint(kind, input);
  return {
    contractVersion: 2,
    kind,
    jobId: ids.job,
    correlationId: ids.correlation,
    inputFingerprintSha256: fingerprint,
    idempotencyKey: `slicer:v2:${kind}:${ids.job}:${fingerprint}`,
    attempt: 1,
    input,
  };
}

describe("SlicingProcessor", () => {
  it("returns inspection metadata and no canonical artifact during discovery", async () => {
    const store = new MemoryStore();
    const engine = new FakeEngine();
    const model = await readFile(
      path.resolve("../../tools/slicing-fixtures/fixtures/single-pla/cube.stl"),
    );
    const sourceHash = sha256(model);
    store.objects.set(`models/${ids.source}/source`, model);
    const input = {
      source: {
        modelFileId: ids.source,
        format: "stl",
        objectKey: `models/${ids.source}/source`,
        contentSha256: sourceHash,
      },
      operation: { mode: "inspect_source" },
      inspectionRevision: "inspection-v1",
      inspectionConfigSha256: "b".repeat(64),
      canonicalizerRevision: "canonicalizer-v1",
      canonicalizerConfigSha256: "c".repeat(64),
    };
    const result = await new SlicingProcessor(store, engine, config).process(
      envelope("model_inspection", input),
    );
    expect(result.outcome.status).toBe("succeeded");
    if (
      result.kind !== "model_inspection" ||
      result.outcome.status !== "succeeded"
    )
      return;
    expect(result.outcome.canonicalGeometry).toBeNull();
    expect(result.outcome.metrics.scaleAssessment).toBe(
      "confirmation_required",
    );
    expect(store.writes).toEqual([]);
    expect(engine.calls).toHaveLength(0);
  });

  it("reuses a persisted reference artifact without regenerating timestamped G-code", async () => {
    const store = new MemoryStore();
    const engine = new FakeEngine();
    const geometry = await readFile(
      path.resolve("../../tools/slicing-fixtures/fixtures/single-pla/cube.stl"),
    );
    const geometryHash = sha256(geometry);
    store.objects.set(`geometries/${ids.geometry}/canonical`, geometry);
    const referenceProfile = new TextEncoder().encode(
      JSON.stringify({ name: "reference-profile" }),
    );
    const printConfig = new TextEncoder().encode(
      JSON.stringify({ name: "print-config" }),
    );
    const referenceHash = sha256(referenceProfile);
    const configHash = sha256(printConfig);
    store.objects.set(
      `slicer-revisions/${referenceHash}/settings.json`,
      referenceProfile,
    );
    store.objects.set(
      `slicer-revisions/${configHash}/settings.json`,
      printConfig,
    );
    const bodyIds = ["body-0001"];
    const job = envelope("reference_slice", {
      geometry: {
        sourceModelFileId: ids.source,
        sourceContentSha256: "d".repeat(64),
        modelGeometryId: ids.geometry,
        canonicalObjectKey: `geometries/${ids.geometry}/canonical`,
        geometrySha256: geometryHash,
        bodyIds,
        selectionSha256: geometrySelectionSha256(bodyIds),
      },
      referenceProfile: {
        revisionId: ids.machineProfile,
        contentSha256: referenceHash,
        slicerEngine: "orcaslicer",
        slicerVersion: "2.4.2",
      },
      printConfig: {
        revisionId: ids.printConfig,
        contentSha256: configHash,
      },
      partsPerPlate: 1,
    }) as SlicingJob;
    const processor = new SlicingProcessor(store, engine, config);

    const first = await processor.process(job);
    const second = await processor.process(job);

    expect(first).toEqual(second);
    expect(first.outcome.status).toBe("succeeded");
    expect(engine.calls).toHaveLength(1);
    expect(store.writes).toEqual([
      `reference-slices/${ids.job}/toolpath.gcode`,
    ]);
  });

  it("reuses immutable candidate occupancy caches and never persists G-code", async () => {
    const store = new MemoryStore();
    const engine = new FakeEngine();
    const geometry = await readFile(
      path.resolve("../../tools/slicing-fixtures/fixtures/single-pla/cube.stl"),
    );
    const geometryHash = sha256(geometry);
    store.objects.set(`geometries/${ids.geometry}/canonical`, geometry);
    const revisionContents = [
      "machine-profile",
      "calibration",
      "print-config",
    ].map((value) => new TextEncoder().encode(JSON.stringify({ name: value })));
    const revisionHashes = revisionContents.map((value) => sha256(value));
    revisionContents.forEach((value, index) =>
      store.objects.set(
        `slicer-revisions/${revisionHashes[index]!}/settings.json`,
        value,
      ),
    );
    const bodyIds = ["body-0001"];
    const base = {
      geometry: {
        sourceModelFileId: ids.source,
        sourceContentSha256: "d".repeat(64),
        modelGeometryId: ids.geometry,
        canonicalObjectKey: `geometries/${ids.geometry}/canonical`,
        geometrySha256: geometryHash,
        bodyIds,
        selectionSha256: geometrySelectionSha256(bodyIds),
      },
      machineId: ids.machine,
      machineProfile: {
        revisionId: ids.machineProfile,
        contentSha256: revisionHashes[0]!,
        slicerEngine: "orcaslicer",
        slicerVersion: "2.4.2",
        productionArtifactFormat: "gcode" as const,
      },
      machineCalibration: {
        revisionId: ids.calibration,
        contentSha256: revisionHashes[1]!,
      },
      printConfig: {
        revisionId: ids.printConfig,
        contentSha256: revisionHashes[2]!,
      },
      partsPerPlate: 2,
      quantity: 3,
      shipmentPlanId: ids.shipment,
      arrangementRevision: {
        revisionId: ids.arrangement,
        contentSha256: "e".repeat(64),
      },
    };
    const targets = [2, 1].map((partsPerPlate) => {
      const identity = machineOccupancyCacheIdentitySha256(base, partsPerPlate);
      return {
        partsPerPlate,
        cacheIdentitySha256: identity,
        analysisObjectKey: `slice-metrics/${identity}/result.json`,
      };
    });
    const job = envelope("candidate_estimate", {
      ...base,
      occupancySliceTargets: targets,
    }) as SlicingJob;
    const processor = new SlicingProcessor(store, engine, config);
    const first = await processor.process(job);
    const second = await processor.process(job);
    expect(first).toEqual(second);
    expect(first.outcome.status).toBe("succeeded");
    expect(engine.calls).toHaveLength(2);
    expect(
      store.writes.filter((key) => key.startsWith("slice-metrics/")),
    ).toHaveLength(2);
    expect(
      [...store.objects.keys()].some((key) => key.startsWith("gcode/")),
    ).toBe(false);
    expect(
      [...store.objects.keys()].some((key) =>
        key.startsWith("reference-slices/"),
      ),
    ).toBe(false);
  });
});
