import { execFile, spawnSync } from "node:child_process";
import { createHash } from "node:crypto";
import { mkdtemp, readFile, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { promisify } from "node:util";
import {
  HeadBucketCommand,
  ListObjectsV2Command,
  S3Client,
} from "@aws-sdk/client-s3";
import { Queue, QueueEvents } from "bullmq";
import {
  SLICING_QUEUE_NAME,
  SlicingResultSchema,
  geometrySelectionSha256,
  machineOccupancyCacheIdentitySha256,
  productionArtifactObjectKey,
  referenceArtifactObjectKey,
  slicingInputFingerprint,
  type SlicingJobKind,
  type SlicingResult,
} from "@taven/slicer-contracts";
import { afterAll, beforeAll, describe, expect, it } from "vitest";
import runtimeLock from "../../../tools/slicing-fixtures/runtime.lock.json" with { type: "json" };
import { readBoundedZipEntries } from "./bounded-zip.js";
import { redisConnection } from "./fixture-runtime.js";
import { S3WorkerObjectStore, sha256 } from "./object-store.js";
import { validateProductionArtifact } from "./orca-engine.js";
import { writeStoredZip } from "../../../tools/slicing-fixtures/scripts/zip-store.mjs";

const execute = promisify(execFile);
const integrationRequested =
  process.env.TAVEN_SLICER_WORKER_INTEGRATION === "1";
const dockerAvailable =
  integrationRequested &&
  spawnSync("docker", ["info"], { stdio: "ignore" }).status === 0;
if (integrationRequested && !dockerAvailable) {
  throw new Error("The enabled slicer-worker integration requires Docker");
}
const runtimeImageAvailable =
  integrationRequested &&
  dockerAvailable &&
  spawnSync("docker", ["image", "inspect", runtimeLock.image.tag], {
    stdio: "ignore",
  }).status === 0;
if (integrationRequested && !runtimeImageAvailable) {
  throw new Error(
    `The enabled slicer-worker integration requires ${runtimeLock.image.tag}`,
  );
}
const integrationEnabled = integrationRequested && runtimeImageAvailable;
const repositoryRoot = path.resolve(
  path.dirname(fileURLToPath(import.meta.url)),
  "../../..",
);
const portBase = 20_000 + (process.pid % 10_000) * 3;
const projectName = `taven-slicer-e2e-${process.pid}`;
const composeEnvironment = {
  ...process.env,
  COMPOSE_PROJECT_NAME: projectName,
  TAVEN_REDIS_PORT: String(portBase),
  TAVEN_MINIO_PORT: String(portBase + 1),
  TAVEN_MINIO_CONSOLE_PORT: String(portBase + 2),
  TAVEN_S3_BUCKET: "taven",
  TAVEN_S3_ACCESS_KEY_ID: "taven",
  TAVEN_S3_SECRET_ACCESS_KEY: "taven-local-only",
  TAVEN_S3_REGION: "us-east-1",
};
const composeFiles = [
  "compose",
  "-f",
  "infra/docker/docker-compose.yml",
  "-f",
  "infra/docker/docker-compose.local.yml",
  "--profile",
  "worker",
];
const ids = {
  source: "10000000-0000-4000-8000-000000000001",
  painted: "10000000-0000-4000-8000-000000000002",
  invalid: "10000000-0000-4000-8000-000000000003",
  geometry: "20000000-0000-4000-8000-000000000001",
  invalidGeometry: "20000000-0000-4000-8000-000000000002",
  referenceProfile: "30000000-0000-4000-8000-000000000001",
  machineProfile: "30000000-0000-4000-8000-000000000002",
  calibration: "30000000-0000-4000-8000-000000000003",
  printConfig: "30000000-0000-4000-8000-000000000004",
  machine: "40000000-0000-4000-8000-000000000001",
  arrangement: "40000000-0000-4000-8000-000000000002",
  shipment: "40000000-0000-4000-8000-000000000003",
  referenceJob: "50000000-0000-4000-8000-000000000001",
  candidateJob: "50000000-0000-4000-8000-000000000002",
  productionJob: "50000000-0000-4000-8000-000000000003",
  reservation: "50000000-0000-4000-8000-000000000004",
} as const;

type RuntimeInputs = {
  sourceBytes: Uint8Array;
  sourceSha256: string;
  referenceBundle: Uint8Array;
  referenceBundleSha256: string;
  machineBundle: Uint8Array;
  machineBundleSha256: string;
  calibrationBundle: Uint8Array;
  calibrationBundleSha256: string;
  printBundle: Uint8Array;
  printBundleSha256: string;
};

let queue: Queue;
let events: QueueEvents;
let store: S3WorkerObjectStore;
let directS3: S3Client;
let sequence = 0;
let inputs: RuntimeInputs;

function digest(value: string): string {
  return createHash("sha256").update(value, "utf8").digest("hex");
}

function bytes(value: unknown): Uint8Array {
  return new TextEncoder().encode(JSON.stringify(value));
}

function normalizedGcodeSha256(value: Uint8Array): string {
  const source = new TextDecoder("utf-8", { fatal: true }).decode(value);
  return sha256(
    new TextEncoder().encode(
      source.replace(
        /^(; generated by OrcaSlicer \S+ on )\d{4}-\d{2}-\d{2} at \d{2}:\d{2}:\d{2}$/mu,
        "$1<timestamp>",
      ),
    ),
  );
}

function normalizedProductionPackage(bytes: Uint8Array, plateCount: number) {
  const entries = readBoundedZipEntries(bytes, {
    label: "Runtime G-code 3MF archive",
    invalidCode: "INVALID_GEOMETRY",
    maximumEntries: 256,
    maximumEntryBytes: 512 * 1024 * 1024,
    maximumTotalBytes: 512 * 1024 * 1024,
  });
  return {
    plates: Array.from({ length: plateCount }, (_, index) => {
      const name = `Metadata/plate_${index + 1}.gcode`;
      const gcode = entries.get(name)!;
      const declaredMd5 = new TextDecoder("utf-8", { fatal: true })
        .decode(entries.get(`${name}.md5`)!)
        .trim();
      return {
        name,
        normalizedGcodeSha256: normalizedGcodeSha256(gcode),
        md5Matches:
          declaredMd5 ===
          createHash("md5").update(gcode).digest("hex").toUpperCase(),
      };
    }),
  };
}

function bundle(...presets: readonly Record<string, unknown>[]): Uint8Array {
  return bytes({ bundleVersion: 1, presets });
}

function envelope(kind: SlicingJobKind, input: unknown, jobId: string) {
  const inputFingerprintSha256 = slicingInputFingerprint(kind, input);
  return {
    contractVersion: 2,
    kind,
    jobId,
    correlationId: jobId,
    inputFingerprintSha256,
    idempotencyKey: `slicer:v2:${kind}:${jobId}:${inputFingerprintSha256}`,
    attempt: 1,
    input,
  };
}

function success(result: SlicingResult) {
  if (result.outcome.status !== "succeeded") {
    throw new Error(
      `Expected ${result.kind} to succeed, received ${result.outcome.code}`,
    );
  }
  return result.outcome;
}

async function compose(arguments_: readonly string[]) {
  return execute("docker", [...composeFiles, ...arguments_], {
    cwd: repositoryRoot,
    env: composeEnvironment,
    maxBuffer: 16 * 1024 * 1024,
  });
}

async function composeOutput(arguments_: readonly string[]): Promise<string> {
  const { stdout } = await compose(arguments_);
  return stdout.trim();
}

async function submit(
  job: ReturnType<typeof envelope>,
): Promise<SlicingResult> {
  sequence += 1;
  const queued = await queue.add("runtime-e2e", job, {
    jobId: `runtime-e2e-${sequence}`,
    attempts: 1,
    removeOnComplete: true,
    removeOnFail: true,
  });
  try {
    return SlicingResultSchema.parse(
      await queued.waitUntilFinished(events, 5 * 60 * 1_000),
    );
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    const diagnostics = await composeOutput([
      "logs",
      "--tail",
      "80",
      "slicer-worker",
      "orca-runner",
    ]).catch(() => "container logs unavailable");
    throw new Error(
      `Slicing job ${job.jobId} failed: ${message}\n${diagnostics}`,
      { cause: error },
    );
  }
}

async function listKeys(prefix: string): Promise<string[]> {
  const response = await directS3.send(
    new ListObjectsV2Command({ Bucket: "taven", Prefix: prefix }),
  );
  return (response.Contents ?? [])
    .map(({ Key }) => Key)
    .filter((key): key is string => key !== undefined)
    .sort();
}

async function assertStoredArtifact(
  artifact: { objectKey: string; sha256: string },
  maximumBytes: number,
): Promise<Uint8Array> {
  const stored = await store.read(
    artifact.objectKey,
    maximumBytes,
    artifact.sha256,
  );
  expect(stored, `${artifact.objectKey} exists`).not.toBeNull();
  expect(stored!.sha256).toBe(artifact.sha256);
  return stored!.bytes;
}

async function writeSnapshot(contents: Uint8Array): Promise<string> {
  const contentSha256 = sha256(contents);
  await store.write(
    `slicer-revisions/${contentSha256}/settings.json`,
    contents,
    "application/json",
  );
  return contentSha256;
}

async function waitForObjectStore(): Promise<void> {
  const deadline = Date.now() + 30_000;
  while (Date.now() < deadline) {
    try {
      await directS3.send(new HeadBucketCommand({ Bucket: "taven" }));
      return;
    } catch {
      await new Promise((resolve) => setTimeout(resolve, 100));
    }
  }
  throw new Error("The integration object store did not become ready");
}

async function loadInputs(): Promise<RuntimeInputs> {
  const [sourceBytes, machine, process, filament] = await Promise.all([
    readFile(
      path.join(
        repositoryRoot,
        "tools/slicing-fixtures/fixtures/single-pla/cube.stl",
      ),
    ),
    readFile(
      path.join(repositoryRoot, "tools/catalog-profiles/resolved/machine.json"),
      "utf8",
    ).then((value) => JSON.parse(value) as Record<string, unknown>),
    readFile(
      path.join(repositoryRoot, "tools/catalog-profiles/resolved/process.json"),
      "utf8",
    ).then((value) => JSON.parse(value) as Record<string, unknown>),
    readFile(
      path.join(
        repositoryRoot,
        "tools/catalog-profiles/resolved/filament-pla.json",
      ),
      "utf8",
    ).then((value) => JSON.parse(value) as Record<string, unknown>),
  ]);
  const referenceBundle = bundle(machine, process, filament);
  const machineBundle = bundle(machine, process, filament);
  const calibrationBundle = bundle({
    elefant_foot_compensation: "0",
    xy_contour_compensation: "0",
    xy_hole_compensation: "0",
  });
  const printBundle = bundle({
    brim_width: "0",
    enable_support: "0",
    layer_height: "0.2",
    sparse_infill_density: "10%",
  });
  return {
    sourceBytes,
    sourceSha256: sha256(sourceBytes),
    referenceBundle,
    referenceBundleSha256: sha256(referenceBundle),
    machineBundle,
    machineBundleSha256: sha256(machineBundle),
    calibrationBundle,
    calibrationBundleSha256: sha256(calibrationBundle),
    printBundle,
    printBundleSha256: sha256(printBundle),
  };
}

async function monitorRequestWorkspace(): Promise<{
  modes: string[];
  childSecurity: string[];
  sandboxIsolation: string[];
}> {
  const command = [
    "attempt=0;",
    'while [ "$attempt" -lt 4000 ]; do',
    "for request in /var/run/taven-orca/request-*; do",
    '[ -d "$request" ] || continue;',
    '[ -d "$request/output" ] && [ -d "$request/tmp" ] && [ -d "$request/tmp/data" ] && [ -d "$request/profiles" ] && [ -d "$request/profiles/settings" ] && [ -d "$request/profiles/filaments" ] || continue;',
    'modes=$(stat -c \'%u:%g:%a\' "$request" "$request/output" "$request/tmp" "$request/tmp/data" "$request/profiles" "$request/profiles/settings" "$request/profiles/filaments");',
    "for status in /proc/[0-9]*/status; do",
    '[ -r "$status" ] || continue;',
    "command=$(tr '\\000' ' ' < \"${status%/status}/cmdline\" 2>/dev/null || true);",
    'case "$command" in *"/opt/orca/AppRun"*)',
    'case "$command" in *"--unshare-pid"*"--unshare-ipc"*"--unshare-uts"*"--ro-bind"*"--tmpfs"*) ;; *) continue ;; esac;',
    'for child_status in "${status%/status}"/root/proc/[0-9]*/status; do',
    '[ -r "$child_status" ] || continue;',
    "child_uid=$(awk '/^Uid:/{print $2}' \"$child_status\");",
    '[ "$child_uid" = "10001" ] || continue;',
    'printf "%s\\n" "$modes";',
    'printf "%s\\n" "$child_uid";',
    'for name in CapInh CapPrm CapEff CapBnd CapAmb; do awk -v name="$name" \'$1 == name ":" { print $2 }\' "$child_status"; done;',
    "awk '/^NoNewPrivs:/{print $2}' \"$child_status\";",
    'printf "%s\\n" "mnt:isolated" "pid:isolated" "ipc:isolated" "uts:isolated";',
    "exit 0;",
    "done;; esac;",
    "done;",
    "done;",
    "attempt=$((attempt + 1));",
    "sleep 0.01;",
    "done; exit 1",
  ].join(" ");
  const result = await composeOutput([
    "exec",
    "-T",
    "orca-runner",
    "/bin/sh",
    "-ec",
    command,
  ]);
  const observation = result.split("\n").filter(Boolean);
  if (observation.length !== 18) {
    throw new Error(
      "The real Orca runner did not expose a complete unprivileged child",
    );
  }
  return {
    modes: observation.slice(0, 7),
    childSecurity: observation.slice(7, 14),
    sandboxIsolation: observation.slice(14),
  };
}

async function assertBrokerSecurity(): Promise<void> {
  const rendered = JSON.parse(
    await composeOutput(["config", "--format", "json"]),
  ) as {
    services: Record<string, { profiles?: string[]; volumes?: unknown[] }>;
  };
  for (const [service, definition] of Object.entries(rendered.services)) {
    if (definition.profiles?.includes("worker")) {
      expect(
        JSON.stringify(definition.volumes ?? []),
        `${service} volumes`,
      ).not.toContain("docker.sock");
    }
  }
  const services = ["slicer-worker", "orca-runner", "slicer-volume-init"];
  const expectedCapabilities = {
    "slicer-worker": [],
    "orca-runner": ["CAP_SETGID", "CAP_SETPCAP", "CAP_SETUID", "CAP_SYS_ADMIN"],
    "slicer-volume-init": ["CAP_CHOWN"],
  } as const;
  let runner: string | undefined;
  for (const service of services) {
    const container = await composeOutput(["ps", "-a", "-q", service]);
    expect(container, `${service} container`).not.toBe("");
    const inspection = JSON.parse(
      await execute("docker", [
        "inspect",
        container,
        "--format",
        "{{json .}}",
      ]).then(({ stdout }) => stdout),
    ) as {
      Config: { User: string };
      HostConfig: {
        CapAdd: string[] | null;
        CapDrop: string[] | null;
        NetworkMode: string;
        Privileged: boolean;
        ReadonlyRootfs: boolean;
      };
      Image: string;
      Mounts: { Destination: string; Source: string }[];
    };
    const caps = inspection.HostConfig.CapAdd ?? [];
    expect(inspection.HostConfig.CapDrop ?? []).toContain("ALL");
    expect([...caps].sort()).toEqual([...expectedCapabilities[service]].sort());
    expect(
      inspection.Mounts.some(
        ({ Destination, Source }) =>
          Destination.includes("docker.sock") || Source.includes("docker.sock"),
      ),
    ).toBe(false);
    if (service === "orca-runner") {
      runner = container;
      expect(inspection.HostConfig.Privileged).toBe(false);
      expect(inspection.HostConfig.NetworkMode).toBe("none");
      expect(inspection.HostConfig.ReadonlyRootfs).toBe(true);
      expect(inspection.Config.User).toBe("0:10001");
      expect(inspection.Image).toBe(
        await execute("docker", [
          "image",
          "inspect",
          runtimeLock.image.tag,
          "--format",
          "{{.Id}}",
        ]).then(({ stdout }) => stdout.trim()),
      );
    }
  }
  expect(runner).toBeDefined();
  expect(
    await composeOutput([
      "exec",
      "-T",
      "orca-runner",
      "stat",
      "-c",
      "%u:%g:%a",
      "/var/run/taven-orca",
    ]),
  ).toBe("10001:10001:770");
}

async function runnerDiagnostics(): Promise<string> {
  return composeOutput([
    "exec",
    "-T",
    "--workdir",
    "/",
    "orca-runner",
    "/bin/sh",
    "-ec",
    "find /var/run/taven-orca/request-* -maxdepth 1 -name diagnostics -type f -exec cat {} \\; 2>/dev/null || true",
  ]);
}

async function assertNoRequestWorkspaces(): Promise<void> {
  expect(
    await composeOutput([
      "exec",
      "-T",
      "orca-runner",
      "/bin/sh",
      "-ec",
      "! find /var/run/taven-orca -maxdepth 1 -type d -name 'request-*' -print -quit | grep -q .",
    ]),
  ).toBe("");
}

async function runSequence(captureWorkspace: boolean) {
  const sourceKey = `models/${ids.source}/source`;
  await store.write(sourceKey, inputs.sourceBytes, "model/stl");
  const sourceInput = {
    source: {
      modelFileId: ids.source,
      format: "stl" as const,
      objectKey: sourceKey,
      contentSha256: inputs.sourceSha256,
    },
    inspectionRevision: "runtime-e2e-inspection-v1",
    inspectionConfigSha256: digest("runtime-e2e-inspection-config"),
    canonicalizerRevision: "runtime-e2e-canonicalizer-v1",
    canonicalizerConfigSha256: digest("runtime-e2e-canonicalizer-config"),
    operation: { mode: "inspect_source" as const },
  };
  const sourceJob = envelope("model_inspection", sourceInput, ids.referenceJob);
  const sourceResult = await submit(sourceJob);
  const sourceOutcome = success(sourceResult);
  expect(sourceResult.kind).toBe("model_inspection");
  expect(sourceOutcome.canonicalGeometry).toBeNull();
  expect(sourceOutcome.findings).toEqual([]);
  const bodyIds = sourceOutcome.bodies.map(({ bodyId }) => bodyId);
  expect(bodyIds).toHaveLength(1);
  const canonicalInput = {
    ...sourceInput,
    operation: {
      mode: "canonicalize_selection" as const,
      sourceInspectionFingerprintSha256: sourceJob.inputFingerprintSha256,
      bodyIds,
      selectionSha256: geometrySelectionSha256(bodyIds),
      confirmedUnitConversion: {
        sourceUnit: "millimeter" as const,
        targetUnit: "millimeter" as const,
        scaleFactorPpm: 1_000_000,
      },
      targetGeometry: {
        modelGeometryId: ids.geometry,
        canonicalObjectKey: `geometries/${ids.geometry}/canonical`,
      },
    },
  };
  const canonicalResult = await submit(
    envelope("model_inspection", canonicalInput, ids.candidateJob),
  );
  const canonicalOutcome = success(canonicalResult);
  if (!canonicalOutcome.canonicalGeometry) {
    throw new Error("Canonicalization did not return immutable geometry");
  }
  const geometry = {
    sourceModelFileId: ids.source,
    sourceContentSha256: inputs.sourceSha256,
    modelGeometryId: ids.geometry,
    canonicalObjectKey: canonicalOutcome.canonicalGeometry.canonicalObjectKey,
    geometrySha256: canonicalOutcome.canonicalGeometry.geometrySha256,
    bodyIds,
    selectionSha256: canonicalOutcome.canonicalGeometry.selectionSha256,
  };
  const referenceInput = {
    geometry,
    referenceProfile: {
      revisionId: ids.referenceProfile,
      contentSha256: inputs.referenceBundleSha256,
      slicerEngine: runtimeLock.engine.name,
      slicerVersion: runtimeLock.engine.version,
    },
    printConfig: {
      revisionId: ids.printConfig,
      contentSha256: inputs.printBundleSha256,
    },
    partsPerPlate: 1,
  };
  const referenceJob = envelope(
    "reference_slice",
    referenceInput,
    ids.referenceJob,
  );
  const workspaceMonitor = captureWorkspace
    ? monitorRequestWorkspace()
    : undefined;
  const referencePromise = submit(referenceJob);
  const referenceResult = await referencePromise;
  if (referenceResult.outcome.status !== "succeeded") {
    await workspaceMonitor?.catch(() => undefined);
    throw new Error(
      `Reference slice failed with ${referenceResult.outcome.code}: ${await runnerDiagnostics()}`,
    );
  }
  const workspaceObservation = await workspaceMonitor;
  const referenceOutcome = success(referenceResult);
  expect(referenceResult.engine.name).toBe(runtimeLock.engine.name);
  expect(referenceOutcome.artifact.objectKey).toBe(
    referenceArtifactObjectKey(referenceJob.inputFingerprintSha256),
  );
  await assertStoredArtifact(referenceOutcome.artifact, 512 * 1024 * 1024);
  const machineBase = {
    geometry,
    machineId: ids.machine,
    machineProfile: {
      revisionId: ids.machineProfile,
      contentSha256: inputs.machineBundleSha256,
      slicerEngine: runtimeLock.engine.name,
      slicerVersion: runtimeLock.engine.version,
      productionArtifactFormat: "gcode_3mf" as const,
    },
    machineCalibration: {
      revisionId: ids.calibration,
      contentSha256: inputs.calibrationBundleSha256,
    },
    printConfig: {
      revisionId: ids.printConfig,
      contentSha256: inputs.printBundleSha256,
    },
    arrangementRevision: {
      revisionId: ids.arrangement,
      contentSha256: digest("runtime-e2e-arrangement"),
    },
    partsPerPlate: 2,
  };
  const occupancySliceTargets = [2].map((partsPerPlate) => {
    const cacheIdentitySha256 = machineOccupancyCacheIdentitySha256(
      machineBase,
      partsPerPlate,
    );
    return {
      partsPerPlate,
      cacheIdentitySha256,
      analysisObjectKey: `slice-metrics/${cacheIdentitySha256}/result.json`,
    };
  });
  const candidateInput = {
    ...machineBase,
    quantity: 2,
    shipmentPlanId: ids.shipment,
    occupancySliceTargets,
  };
  const candidateResult = await submit(
    envelope("candidate_estimate", candidateInput, ids.candidateJob),
  );
  const candidateOutcome = success(candidateResult);
  expect(candidateOutcome.occupancySlices).toHaveLength(1);
  expect(await listKeys("gcode/")).toEqual([]);
  expect(await listKeys("slice-metrics/")).toEqual([
    occupancySliceTargets[0]!.analysisObjectKey,
  ]);
  await Promise.all(
    candidateOutcome.occupancySlices.map(({ artifact }) =>
      assertStoredArtifact(artifact, 64 * 1024),
    ),
  );
  const productionInput = {
    ...machineBase,
    quantity: 3,
    acceptedJobId: ids.productionJob,
    productionReservationId: ids.reservation,
  };
  const productionJob = envelope(
    "production_slice",
    productionInput,
    ids.productionJob,
  );
  const productionResult = await submit(productionJob);
  const productionOutcome = success(productionResult);
  expect(productionOutcome.metrics.plateCount).toBe(2);
  expect(productionOutcome.artifact.objectKey).toBe(
    productionArtifactObjectKey(ids.productionJob, "gcode_3mf"),
  );
  const productionArtifact = await assertStoredArtifact(
    productionOutcome.artifact,
    512 * 1024 * 1024,
  );
  validateProductionArtifact(
    productionArtifact,
    "gcode_3mf",
    2,
    runtimeLock.engine.version,
    512 * 1024 * 1024,
  );
  return {
    source: sourceOutcome,
    canonical: canonicalOutcome,
    reference: referenceOutcome,
    candidate: candidateOutcome,
    production: productionOutcome,
    normalizedProductionPackage: normalizedProductionPackage(
      productionArtifact,
      productionOutcome.metrics.plateCount,
    ),
    workspaceModes: workspaceObservation?.modes,
    childSecurity: workspaceObservation?.childSecurity,
    sandboxIsolation: workspaceObservation?.sandboxIsolation,
    outputKeys: [
      referenceOutcome.artifact.objectKey,
      ...occupancySliceTargets.map(
        ({ analysisObjectKey }) => analysisObjectKey,
      ),
      productionOutcome.artifact.objectKey,
    ],
  };
}

async function assertInspectionFailures(): Promise<void> {
  const productionKeysBefore = await listKeys("gcode/");
  const paintedSource = path.join(
    repositoryRoot,
    "tools/slicing-fixtures/fixtures/painted-multimaterial/source",
  );
  const temporaryDirectory = await mkdtemp(
    path.join(tmpdir(), "taven-painted-fixture-"),
  );
  const archive = path.join(temporaryDirectory, "painted.3mf");
  let paintedBytes: Uint8Array;
  try {
    await writeStoredZip(archive, paintedSource, [
      "[Content_Types].xml",
      "_rels/.rels",
      "3D/3dmodel.model",
    ]);
    paintedBytes = await readFile(archive);
  } finally {
    await rm(temporaryDirectory, { recursive: true, force: true });
  }
  const paintedKey = `models/${ids.painted}/source`;
  await store.write(paintedKey, paintedBytes, "model/3mf");
  const paintedResult = await submit(
    envelope(
      "model_inspection",
      {
        source: {
          modelFileId: ids.painted,
          format: "3mf",
          objectKey: paintedKey,
          contentSha256: sha256(paintedBytes),
        },
        inspectionRevision: "runtime-e2e-inspection-v1",
        inspectionConfigSha256: digest("runtime-e2e-inspection-config"),
        canonicalizerRevision: "runtime-e2e-canonicalizer-v1",
        canonicalizerConfigSha256: digest("runtime-e2e-canonicalizer-config"),
        operation: { mode: "inspect_source" },
      },
      ids.referenceJob,
    ),
  );
  const paintedOutcome = success(paintedResult);
  expect(paintedOutcome.canonicalGeometry).toBeNull();
  expect(paintedOutcome.findings).toEqual(
    expect.arrayContaining([
      expect.objectContaining({
        code: "PAINTED_OR_MULTIMATERIAL",
        severity: "blocking",
        phase: "inspection",
      }),
    ]),
  );
  expect(await listKeys(`geometries/${ids.painted}/`)).toEqual([]);

  const invalidBytes = await readFile(
    path.join(
      repositoryRoot,
      "tools/slicing-fixtures/fixtures/invalid-geometry/open-triangle.stl",
    ),
  );
  const invalidKey = `models/${ids.invalid}/source`;
  const invalidSha256 = sha256(invalidBytes);
  await store.write(invalidKey, invalidBytes, "model/stl");
  const invalidSourceInput = {
    source: {
      modelFileId: ids.invalid,
      format: "stl" as const,
      objectKey: invalidKey,
      contentSha256: invalidSha256,
    },
    inspectionRevision: "runtime-e2e-inspection-v1",
    inspectionConfigSha256: digest("runtime-e2e-inspection-config"),
    canonicalizerRevision: "runtime-e2e-canonicalizer-v1",
    canonicalizerConfigSha256: digest("runtime-e2e-canonicalizer-config"),
    operation: { mode: "inspect_source" as const },
  };
  const invalidSourceJob = envelope(
    "model_inspection",
    invalidSourceInput,
    ids.candidateJob,
  );
  const invalidSourceResult = await submit(invalidSourceJob);
  if (invalidSourceResult.outcome.status === "failed") {
    expect(invalidSourceResult.outcome).toMatchObject({
      failureClass: "deterministic_invalid",
      code: "INVALID_MODEL",
      retryable: false,
    });
    expect(await listKeys("gcode/")).toEqual(productionKeysBefore);
    await assertNoRequestWorkspaces();
    return;
  }
  const invalidSourceOutcome = success(invalidSourceResult);
  const bodyIds = invalidSourceOutcome.bodies.map(({ bodyId }) => bodyId);
  const invalidCanonicalResult = await submit(
    envelope(
      "model_inspection",
      {
        ...invalidSourceInput,
        operation: {
          mode: "canonicalize_selection" as const,
          sourceInspectionFingerprintSha256:
            invalidSourceJob.inputFingerprintSha256,
          bodyIds,
          selectionSha256: geometrySelectionSha256(bodyIds),
          confirmedUnitConversion: {
            sourceUnit: "millimeter" as const,
            targetUnit: "millimeter" as const,
            scaleFactorPpm: 1_000_000,
          },
          targetGeometry: {
            modelGeometryId: ids.invalidGeometry,
            canonicalObjectKey: `geometries/${ids.invalidGeometry}/canonical`,
          },
        },
      },
      ids.productionJob,
    ),
  );
  if (invalidCanonicalResult.outcome.status === "failed") {
    expect(invalidCanonicalResult.outcome).toMatchObject({
      failureClass: "deterministic_invalid",
      code: "INVALID_GEOMETRY",
      retryable: false,
    });
    await assertNoRequestWorkspaces();
    return;
  }
  const canonical = invalidCanonicalResult.outcome.canonicalGeometry;
  if (!canonical)
    throw new Error("Invalid geometry did not reach canonical form");
  const invalidReference = envelope(
    "reference_slice",
    {
      geometry: {
        sourceModelFileId: ids.invalid,
        sourceContentSha256: invalidSha256,
        modelGeometryId: ids.invalidGeometry,
        canonicalObjectKey: canonical.canonicalObjectKey,
        geometrySha256: canonical.geometrySha256,
        bodyIds,
        selectionSha256: canonical.selectionSha256,
      },
      referenceProfile: {
        revisionId: ids.referenceProfile,
        contentSha256: inputs.referenceBundleSha256,
        slicerEngine: runtimeLock.engine.name,
        slicerVersion: runtimeLock.engine.version,
      },
      printConfig: {
        revisionId: ids.printConfig,
        contentSha256: inputs.printBundleSha256,
      },
      partsPerPlate: 1,
    },
    ids.productionJob,
  );
  const invalidReferenceResult = await submit(invalidReference);
  expect(invalidReferenceResult.outcome).toMatchObject({
    status: "failed",
    failureClass: "deterministic_invalid",
    code: "INVALID_GEOMETRY",
    retryable: false,
  });
  expect(
    await listKeys(
      `reference-slices/${invalidReference.inputFingerprintSha256}/`,
    ),
  ).toEqual([]);
  await assertNoRequestWorkspaces();
}

describe.skipIf(!integrationEnabled)("pinned Orca runtime end to end", () => {
  beforeAll(
    async () => {
      await compose(["build", "slicer-worker"]);
      await compose([
        "up",
        "--detach",
        "redis",
        "minio",
        "minio-init",
        "slicer-volume-init",
        "orca-runner",
        "slicer-worker",
      ]);
      const connection = redisConnection(`redis://127.0.0.1:${portBase}`);
      queue = new Queue(SLICING_QUEUE_NAME, { connection });
      events = new QueueEvents(SLICING_QUEUE_NAME, { connection });
      await events.waitUntilReady();
      const storage = {
        endpoint: `http://127.0.0.1:${portBase + 1}`,
        region: "us-east-1",
        bucket: "taven",
        accessKeyId: "taven",
        secretAccessKey: "taven-local-only",
        forcePathStyle: true,
      };
      store = new S3WorkerObjectStore(storage);
      directS3 = new S3Client({
        ...storage,
        credentials: {
          accessKeyId: storage.accessKeyId,
          secretAccessKey: storage.secretAccessKey,
        },
      });
      await waitForObjectStore();
      inputs = await loadInputs();
      await Promise.all([
        writeSnapshot(inputs.referenceBundle),
        writeSnapshot(inputs.machineBundle),
        writeSnapshot(inputs.calibrationBundle),
        writeSnapshot(inputs.printBundle),
      ]);
    },
    10 * 60 * 1_000,
  );

  afterAll(async () => {
    await Promise.all([events?.close(), queue?.close(), directS3?.destroy()]);
    await compose(["down", "--volumes", "--remove-orphans"]);
  }, 60_000);

  it(
    "uses the production v2 worker, broker, and pinned image twice from clean workspaces",
    async () => {
      await assertBrokerSecurity();
      const first = await runSequence(true);
      expect(first.workspaceModes).toEqual(Array(7).fill("10001:10001:770"));
      expect(first.childSecurity).toEqual([
        "10001",
        "0000000000000000",
        "0000000000000000",
        "0000000000000000",
        "0000000000000000",
        "0000000000000000",
        "1",
      ]);
      expect(first.sandboxIsolation).toEqual([
        "mnt:isolated",
        "pid:isolated",
        "ipc:isolated",
        "uts:isolated",
      ]);
      await Promise.all(first.outputKeys.map((key) => store.delete(key)));
      const second = await runSequence(false);
      expect({
        source: second.source,
        canonical: second.canonical,
        reference: second.reference,
        candidate: second.candidate,
        production: {
          ...second.production,
          artifact: {
            format: second.production.artifact.format,
            objectKey: second.production.artifact.objectKey,
          },
        },
        normalizedProductionPackage: second.normalizedProductionPackage,
      }).toEqual({
        source: first.source,
        canonical: first.canonical,
        reference: first.reference,
        candidate: first.candidate,
        production: {
          ...first.production,
          artifact: {
            format: first.production.artifact.format,
            objectKey: first.production.artifact.objectKey,
          },
        },
        normalizedProductionPackage: first.normalizedProductionPackage,
      });
      await assertNoRequestWorkspaces();
    },
    10 * 60 * 1_000,
  );

  it(
    "blocks painted input and rejects malformed geometry deterministically",
    async () => {
      await assertInspectionFailures();
    },
    5 * 60 * 1_000,
  );
});
