import { spawnSync } from "node:child_process";
import { createHash } from "node:crypto";
import {
  chmod,
  copyFile,
  mkdir,
  mkdtemp,
  readFile,
  readdir,
  writeFile,
} from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import process from "node:process";
import { buildProfileBundle, fixtureRoot, stableJson } from "./profile-lib.mjs";
import { writeStoredZip } from "./zip-store.mjs";

const recordArgument = process.argv.indexOf("--record");
const recordDirectory =
  recordArgument === -1
    ? undefined
    : path.resolve(process.argv[recordArgument + 1]);
if (recordArgument !== -1 && !process.argv[recordArgument + 1]) {
  throw new Error("--record requires an output directory");
}

const lock = JSON.parse(
  await readFile(path.join(fixtureRoot, "runtime.lock.json"), "utf8"),
);
const { manifest } = await buildProfileBundle();
if (manifest.bundleSha256 !== lock.profiles.bundleSha256) {
  throw new Error(
    "Runtime lock profile digest does not match the resolved bundle",
  );
}
if (manifest.upstream.revision !== lock.profiles.upstreamRevision) {
  throw new Error(
    "Runtime lock profile revision does not match the resolved bundle",
  );
}

const profileDirectory = path.join(fixtureRoot, "profiles", "resolved");
const fixtureDirectory = path.join(fixtureRoot, "fixtures");
const cases = [
  {
    name: "single-pla",
    fixture: "cube.stl",
    operation: "slice",
    cloneCount: 1,
    trianglesPerObject: 12,
  },
  {
    name: "quantity-pla",
    fixture: "cube.stl",
    operation: "slice",
    cloneCount: 2,
    trianglesPerObject: 12,
  },
  {
    name: "painted-multimaterial",
    fixture: "painted-multimaterial.3mf",
    operation: "slice",
    cloneCount: 1,
    filamentCount: 2,
  },
  {
    name: "invalid-geometry",
    fixture: "open-triangle.stl",
    operation: "slice",
    cloneCount: 1,
    invalid: true,
  },
];

function digest(value) {
  return createHash("sha256").update(value).digest("hex");
}

function normalizedResult(result) {
  if (!result) {
    return null;
  }
  return {
    returnCode: result.return_code,
    error: result.error_string,
    layerHeight: result.layer_height,
    plateIndex: result.plate_index,
    sparseInfillDensity: result.sparse_infill_density,
    wallLoops: result.wall_loops,
    slicedPlates: (result.sliced_plates ?? []).map((plate) => ({
      id: plate.id,
      triangleCount: plate.triangle_count,
      warning: plate.warning_message,
    })),
  };
}

function secondsFromDuration(value) {
  const hours = Number(value.match(/(\d+)h/)?.[1] ?? 0);
  const minutes = Number(value.match(/(\d+)m/)?.[1] ?? 0);
  const seconds = Number(value.match(/(\d+)s/)?.[1] ?? 0);
  return hours * 3600 + minutes * 60 + seconds;
}

function normalizeDiagnostics(value) {
  return value
    .split("\n")
    .map((line) => line.trimEnd())
    .filter(Boolean)
    .map((line) =>
      line.replace(/\d{4}-\d{2}-\d{2}[ T]\d{2}:\d{2}:\d{2}/g, "<timestamp>"),
    );
}

function parseGcode(source) {
  const normalized = source.replace(
    /^; generated by OrcaSlicer .+$/m,
    `; generated by OrcaSlicer ${lock.engine.version} on <timestamp>`,
  );
  const estimate = source.match(/total estimated time: ([^\n]+)/)?.[1];
  const filamentMillimeters = source.match(
    /; filament used \[mm\] = ([\d.]+)/,
  )?.[1];
  const filamentCubicCentimeters = source.match(
    /; filament used \[cm3\] = ([\d.]+)/,
  )?.[1];
  const filamentSlots = source
    .match(/^; filament: ([\d,]+)$/m)?.[1]
    ?.split(",")
    .map(Number);
  return {
    normalizedSha256: digest(normalized),
    estimatedSeconds: estimate ? secondsFromDuration(estimate) : null,
    filamentMillimeters: filamentMillimeters
      ? Number(filamentMillimeters)
      : null,
    filamentCubicCentimeters: filamentCubicCentimeters
      ? Number(filamentCubicCentimeters)
      : null,
    filamentSlots: filamentSlots ?? [],
  };
}

function usesExpectedFilaments(output, filamentCount) {
  if (filamentCount === undefined) {
    return true;
  }
  const slots = [...new Set(output.filamentSlots)].sort(
    (left, right) => left - right,
  );
  return (
    slots.length === filamentCount &&
    slots.every((slot, index) => slot === index + 1)
  );
}

function hasExpectedCloneEvidence(fixtureCase, resultFile) {
  if (fixtureCase.trianglesPerObject === undefined) {
    return true;
  }
  const slicedPlates = resultFile?.sliced_plates;
  return (
    Array.isArray(slicedPlates) &&
    slicedPlates.length > 0 &&
    slicedPlates.every(
      (plate) =>
        Number.isInteger(plate.triangle_count) && plate.triangle_count > 0,
    ) &&
    slicedPlates.reduce((total, plate) => total + plate.triangle_count, 0) ===
      fixtureCase.trianglesPerObject * fixtureCase.cloneCount
  );
}

function validateExecution(fixtureCase, execution, resultFile, outputs) {
  if (execution.error) {
    throw new Error(
      `Could not execute ${fixtureCase.name}: ${execution.error.message}`,
      { cause: execution.error },
    );
  }
  if (execution.status === null || execution.signal !== null) {
    throw new Error(
      `OrcaSlicer did not exit normally for ${fixtureCase.name} (status ${execution.status}, signal ${execution.signal ?? "none"})`,
    );
  }

  if (fixtureCase.invalid) {
    if (
      execution.status === 0 ||
      !resultFile ||
      !Number.isFinite(resultFile.return_code) ||
      resultFile.return_code >= 0 ||
      outputs.length !== 0
    ) {
      throw new Error(
        `Invalid fixture ${fixtureCase.name} did not produce the expected failure`,
      );
    }
    return;
  }

  if (
    execution.status !== 0 ||
    resultFile?.return_code !== 0 ||
    !hasExpectedCloneEvidence(fixtureCase, resultFile) ||
    outputs.length === 0 ||
    outputs.some(
      (output) =>
        !Number.isFinite(output.estimatedSeconds) ||
        output.estimatedSeconds <= 0 ||
        !Number.isFinite(output.filamentMillimeters) ||
        output.filamentMillimeters <= 0 ||
        !Number.isFinite(output.filamentCubicCentimeters) ||
        output.filamentCubicCentimeters <= 0 ||
        !usesExpectedFilaments(output, fixtureCase.filamentCount),
    )
  ) {
    throw new Error(
      `Fixture ${fixtureCase.name} did not produce a successful slice`,
    );
  }
}

async function prepareInput(directory, fixtureCase) {
  const destination = path.join(directory, fixtureCase.fixture);
  if (fixtureCase.name === "painted-multimaterial") {
    const source = path.join(
      fixtureDirectory,
      "painted-multimaterial",
      "source",
    );
    await writeStoredZip(destination, source, [
      "[Content_Types].xml",
      "_rels/.rels",
      "3D/3dmodel.model",
    ]);
  } else {
    const source = path.join(
      fixtureDirectory,
      fixtureCase.name === "invalid-geometry"
        ? "invalid-geometry"
        : "single-pla",
      fixtureCase.fixture,
    );
    await copyFile(source, destination);
  }
  return destination;
}

async function runCase(runRoot, fixtureCase) {
  const inputDirectory = path.join(runRoot, fixtureCase.name, "input");
  const outputDirectory = path.join(runRoot, fixtureCase.name, "output");
  await mkdir(inputDirectory, { recursive: true });
  await mkdir(outputDirectory, { recursive: true });
  await chmod(outputDirectory, 0o777);
  const input = await prepareInput(inputDirectory, fixtureCase);
  let secondaryFilamentDigest = null;
  if (fixtureCase.name === "painted-multimaterial") {
    const secondaryFilament = JSON.parse(
      await readFile(path.join(profileDirectory, "filament.json"), "utf8"),
    );
    secondaryFilament.name = "Taven fixture blue PLA";
    secondaryFilament.setting_id = "TAVEN_FIXTURE_BLUE";
    secondaryFilament.filament_id = "TAVEN_FIXTURE_BLUE";
    secondaryFilament.filament_settings_id = ["Taven fixture blue PLA"];
    secondaryFilament.filament_colour = ["#0066CC"];
    const secondaryContents = stableJson(secondaryFilament);
    await writeFile(
      path.join(inputDirectory, "filament-secondary.json"),
      secondaryContents,
    );
    secondaryFilamentDigest = digest(secondaryContents);
  }

  const runtimeProfileDirectory = "/opt/taven/profiles";
  const filamentPath = `${runtimeProfileDirectory}/filament.json`;
  const command = [
    "--debug",
    "2",
    "--slice",
    "0",
    "--outputdir",
    "/output",
    "--datadir",
    "/tmp/data",
    "--load-settings",
    `${runtimeProfileDirectory}/process.json;${runtimeProfileDirectory}/machine.json`,
    "--load-filaments",
    fixtureCase.filamentCount === 2
      ? `${filamentPath};/input/filament-secondary.json`
      : filamentPath,
  ];
  if (fixtureCase.cloneCount > 1) {
    command.push(
      "--arrange",
      "1",
      "--clone-objects",
      String(fixtureCase.cloneCount),
    );
  }
  if (fixtureCase.name === "painted-multimaterial") {
    command.push("--allow-multicolor-oneplate");
  }
  command.push(`/input/${fixtureCase.fixture}`);

  const execution = spawnSync(
    "docker",
    [
      "run",
      "--rm",
      "--platform",
      lock.platform,
      "--network",
      "none",
      "--read-only",
      "--cap-drop",
      "ALL",
      "--security-opt",
      "no-new-privileges",
      "--pids-limit",
      "256",
      "--tmpfs",
      "/tmp:rw,nosuid,nodev,size=536870912,mode=1777",
      "--tmpfs",
      "/work:rw,nosuid,nodev,size=67108864,mode=0700,uid=10001,gid=10001",
      "--mount",
      `type=bind,src=${inputDirectory},dst=/input,readonly`,
      "--mount",
      `type=bind,src=${outputDirectory},dst=/output`,
      lock.image.tag,
      ...command,
    ],
    { encoding: "utf8", maxBuffer: 16 * 1024 * 1024 },
  );

  const files = await readdir(outputDirectory);
  const resultFile = files.includes("result.json")
    ? JSON.parse(
        await readFile(path.join(outputDirectory, "result.json"), "utf8"),
      )
    : null;
  const gcodeFiles = files.filter((file) => file.endsWith(".gcode")).sort();
  const outputs = await Promise.all(
    gcodeFiles.map(async (file) => {
      const source = await readFile(path.join(outputDirectory, file), "utf8");
      if (source.trim().length === 0) {
        throw new Error(`Fixture ${fixtureCase.name} produced empty ${file}`);
      }
      return { file, ...parseGcode(source) };
    }),
  );
  validateExecution(fixtureCase, execution, resultFile, outputs);
  const inputContents = await readFile(input);
  const paintedSource =
    fixtureCase.name === "painted-multimaterial"
      ? await readFile(
          path.join(
            fixtureDirectory,
            "painted-multimaterial",
            "source",
            "3D",
            "3dmodel.model",
          ),
          "utf8",
        )
      : "";
  const paintCodes = [
    ...paintedSource.matchAll(/mmu_segmentation="([0-9a-f]+)"/g),
  ].map((match) => Number.parseInt(match[1], 16) >> 2);

  return {
    schemaVersion: 1,
    case: fixtureCase.name,
    engine: {
      name: lock.engine.name,
      version: lock.engine.version,
      imageDigest: lock.image.ociDigest,
    },
    profiles: {
      upstreamRevision: manifest.upstream.revision,
      bundleSha256: manifest.bundleSha256,
    },
    input: {
      file: fixtureCase.fixture,
      sha256: digest(inputContents),
      secondaryFilamentSha256: secondaryFilamentDigest,
      cloneCount: fixtureCase.cloneCount,
      paintedExtruders: [...new Set(paintCodes)].sort(
        (left, right) => left - right,
      ),
      expectedInvalidGeometry: fixtureCase.invalid ?? false,
    },
    execution: {
      exitCode: execution.status,
      signal: execution.signal,
      stdout: normalizeDiagnostics(execution.stdout ?? ""),
      stderr: normalizeDiagnostics(execution.stderr ?? ""),
      result: normalizedResult(resultFile),
    },
    outputs,
  };
}

const firstRoot = await mkdtemp(path.join(os.tmpdir(), "taven-orca-corpus-a-"));
const secondRoot = await mkdtemp(
  path.join(os.tmpdir(), "taven-orca-corpus-b-"),
);
const first = [];
const second = [];
for (const fixtureCase of cases) {
  first.push(await runCase(firstRoot, fixtureCase));
  second.push(await runCase(secondRoot, fixtureCase));
}

const instability = cases.filter(
  (_fixtureCase, index) =>
    stableJson(first[index]) !== stableJson(second[index]),
);
if (instability.length > 0) {
  throw new Error(
    `Corpus is not stable across two clean runs: ${instability.map(({ name }) => name).join(", ")}`,
  );
}

const destinationDirectory =
  recordDirectory ?? path.join(fixtureRoot, "expected");
if (recordDirectory) {
  await mkdir(recordDirectory, { recursive: true });
}
const drift = [];
for (const [index, fixtureCase] of cases.entries()) {
  const expectedPath = path.join(
    destinationDirectory,
    `${fixtureCase.name}.json`,
  );
  const actual = stableJson(first[index]);
  if (recordDirectory) {
    await writeFile(expectedPath, actual);
    continue;
  }
  let expected;
  try {
    expected = await readFile(expectedPath, "utf8");
  } catch {
    drift.push(fixtureCase.name);
    continue;
  }
  if (expected !== actual) {
    drift.push(fixtureCase.name);
  }
}
if (drift.length > 0) {
  throw new Error(
    `Corpus output changed for ${drift.join(", ")}. Build old and new runtimes and review the expected JSON diff before updating.`,
  );
}
console.log(
  `${recordDirectory ? "Recorded" : "Verified"} ${cases.length} fixtures across two clean runs with profile ${manifest.bundleSha256}.`,
);
