import { mkdtemp, mkdir, rm, writeFile } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { describe, expect, it } from "vitest";
import { checkBoundaries } from "./check-boundaries.mjs";

async function fixture() {
  const root = await mkdtemp(path.join(os.tmpdir(), "taven-boundaries-"));
  await mkdir(path.join(root, "packages/core/src"), { recursive: true });
  await mkdir(path.join(root, "packages/slicer-contracts/src"), {
    recursive: true,
  });
  await mkdir(path.join(root, "packages/openapi-client/generated"), {
    recursive: true,
  });
  await writeFile(
    path.join(root, "packages/openapi-client/generated/schema.ts"),
    "// This file was auto-generated by openapi-typescript\n",
  );
  return root;
}

describe("checkBoundaries", () => {
  it("reports runtime dependencies and forbidden core imports", async () => {
    const root = await fixture();
    try {
      await writeFile(
        path.join(root, "packages/core/package.json"),
        JSON.stringify({ dependencies: { prisma: "1.0.0" } }),
      );
      await writeFile(
        path.join(root, "packages/core/src/forbidden.ts"),
        'import { PrismaClient } from "@prisma/client";\nvoid import("bullmq");\n',
      );

      const violations = await checkBoundaries(root);
      expect(violations).toEqual(
        expect.arrayContaining([
          "packages/core must not have runtime dependency 'prisma'",
          "packages/core/src/forbidden.ts imports forbidden '@prisma/client'",
          "packages/core/src/forbidden.ts imports forbidden 'bullmq'",
        ]),
      );
    } finally {
      await rm(root, { recursive: true, force: true });
    }
  });

  it("allows relative domain imports and Vitest in test files", async () => {
    const root = await fixture();
    try {
      await writeFile(
        path.join(root, "packages/core/package.json"),
        JSON.stringify({}),
      );
      await writeFile(
        path.join(root, "packages/core/src/value.ts"),
        "export const value = 1;\n",
      );
      await writeFile(
        path.join(root, "packages/core/src/value.test.ts"),
        'import { describe, expect, it } from "vitest";\nimport { value } from "./value.js";\nit("works", () => expect(value).toBe(1));\n',
      );

      expect(await checkBoundaries(root)).toEqual([]);
    } finally {
      await rm(root, { recursive: true, force: true });
    }
  });

  it("resolves relative imports before enforcing package boundaries", async () => {
    const root = await fixture();
    try {
      await writeFile(
        path.join(root, "packages/core/package.json"),
        JSON.stringify({}),
      );
      await writeFile(
        path.join(root, "packages/core/src/relative.ts"),
        'import "../../openapi-client/generated/schema.js";\nimport "../../slicer-contracts/src/index.js";\n',
      );

      expect(await checkBoundaries(root)).toEqual(
        expect.arrayContaining([
          "packages/core/src/relative.ts imports forbidden '../../openapi-client/generated/schema.js'",
          "packages/core/src/relative.ts imports forbidden '../../slicer-contracts/src/index.js'",
        ]),
      );
    } finally {
      await rm(root, { recursive: true, force: true });
    }
  });

  it("ignores import-looking comments, strings, and template literal text", async () => {
    const root = await fixture();
    try {
      await writeFile(
        path.join(root, "packages/core/package.json"),
        JSON.stringify({}),
      );
      await writeFile(
        path.join(root, "packages/core/src/comment-fixture.ts"),
        [
          '// import { PrismaClient } from "@prisma/client";',
          '/* export * from "@nestjs/common"; void import("bullmq"); */',
          'const importExample = "require(\\"redis\\")";',
          'const templateExample = `import("@taven/backend") from text`;',
          'const nestedTemplate = `${"export * from \\"vue\\""}`;',
          'const regexpExample = /import\\("@prisma\\/client"\\)/;',
          'const moduleName = "@prisma/client";',
          "void import(moduleName);",
          "void require(moduleName);",
        ].join("\n"),
      );
      await writeFile(
        path.join(root, "packages/core/src/component.vue"),
        [
          '<template>{{ `import("@prisma/client")` }}</template>',
          '<!-- <script>import "@prisma/client";</script> -->',
        ].join("\n"),
      );

      expect(await checkBoundaries(root)).toEqual([]);
    } finally {
      await rm(root, { recursive: true, force: true });
    }
  });

  it("detects real import forms in TypeScript and Vue scripts", async () => {
    const root = await fixture();
    try {
      await writeFile(
        path.join(root, "packages/core/package.json"),
        JSON.stringify({}),
      );
      await writeFile(
        path.join(root, "packages/core/src/imports.ts"),
        [
          'import {} from "@prisma/client";',
          'export {} from "@nestjs/common";',
          'void import("bullmq");',
          'void require("redis");',
          'type Prisma = import("prisma").Prisma;',
        ].join("\n"),
      );
      await writeFile(
        path.join(root, "packages/core/src/component.vue"),
        [
          "<template>require('redis')</template>",
          '<script setup lang="ts">',
          'import {} from "vue";',
          "</script>",
        ].join("\n"),
      );

      expect(await checkBoundaries(root)).toEqual(
        expect.arrayContaining([
          "packages/core/src/imports.ts imports forbidden '@prisma/client'",
          "packages/core/src/imports.ts imports forbidden '@nestjs/common'",
          "packages/core/src/imports.ts imports forbidden 'bullmq'",
          "packages/core/src/imports.ts imports forbidden 'redis'",
          "packages/core/src/imports.ts imports forbidden 'prisma'",
          "packages/core/src/component.vue imports forbidden 'vue'",
        ]),
      );
    } finally {
      await rm(root, { recursive: true, force: true });
    }
  });

  it("parses slicer-contract imports without matching documentation text", async () => {
    const root = await fixture();
    try {
      await writeFile(
        path.join(root, "packages/core/package.json"),
        JSON.stringify({}),
      );
      await writeFile(
        path.join(root, "packages/slicer-contracts/src/examples.ts"),
        [
          '// Do not import("@taven/backend") here.',
          'const example = "require(\\"@taven/slicer-worker\\")";',
        ].join("\n"),
      );

      expect(await checkBoundaries(root)).toEqual([]);

      await writeFile(
        path.join(root, "packages/slicer-contracts/src/forbidden.ts"),
        'export type { AppModule } from "@taven/backend";\n',
      );

      expect(await checkBoundaries(root)).toContain(
        "packages/slicer-contracts/src/forbidden.ts imports an application implementation",
      );
    } finally {
      await rm(root, { recursive: true, force: true });
    }
  });
});
